### ISSUE TITLE
[Bug] use_default_actions = false and use_default_prompts = false still create slash cmds and keybindings

### ISSUE THREAD

**Issue by olimorris** [olimorris/codecompanion.nvim#105]
### Discussed in https://github.com/olimorris/codecompanion.nvim/discussions/104

<div type='discussions-op-text'>

<sup>Originally posted by **isaksamsten** August 21, 2024</sup>
Hi!

When setting the above "use_default_actions = false and use_default_promts = false" the actions and prompts still load as "slash" commands and keybindings. Is this a bug or intentional?

Best,
Isak</div>

**Comment by olimorris** [comment]
So you should be able to set `use_default_prompts = false` and add your own default_prompts in your config.

This won't stop the slash cmds from being added (that's a bug I've just spotted), but it stops the default prompts from being added as we tag them with `default_prompt = true` in the [config](https://github.com/olimorris/codecompanion.nvim/blob/d92baf01a317b4b7bc6658ac1afad91a82033f13/lua/codecompanion/config.lua#L226) and never add them when we setup the [action palette](https://github.com/olimorris/codecompanion.nvim/blob/d92baf01a317b4b7bc6658ac1afad91a82033f13/lua/codecompanion/actions.lua#L262).

**Comment by isaksamsten** [comment]
To avoid keybindings to be added if `use_default_prompts = false`, something like this should go into `prompt.lua`:

```lua
---@return CodeCompanion.Prompts
function Prompts:setup()
  --Loop through the prompts
  local global_config = require("codecompanion").config
  for _, config in pairs(self.prompts) do
    if config.opts and config.opts.mapping then
      if not global_config.opts.use_default_prompts and config.opts.default_prompt then
        goto continue
      end
      if config.opts.modes and type(config.opts.modes) == "table" then
        for _, mode in ipairs(config.opts.modes) do
          map(config, mode)
        end
      else
        map(config, "n")
      end
    end
    ::continue::
  end
```

**Comment by olimorris** [comment]
Good spot. This has highlighted what a mess this default prompts and actions is currently

**Comment by olimorris** [comment]
@isaksamsten also fancy Pr'ing this?
