### ISSUE TITLE
[Bug]: Anthropic adapter with Chat strategy throws Error when referencing #buffer

### ISSUE THREAD

**Issue by ivo-toby** [olimorris/codecompanion.nvim#123]
### Your `minimal.lua` config

```
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--single-branch",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)

-- Your CodeCompanion setup
local plugins = {
	{
		"olimorris/codecompanion.nvim",
		dependencies = {
			{ "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
			"nvim-lua/plenary.nvim",
			"nvim-telescope/telescope.nvim",
			{
				"stevearc/dressing.nvim",
				opts = {},
			},
		},
		opts = {
			-- Refer to: https://github.com/olimorris/codecompanion.nvim/blob/main/lua/codecompanion/config.lua
			strategies = { -- Change the adapters as required
				chat = { adapter = "anthropic" },
				inline = { adapter = "anthropic" },
				agent = { adapter = "anthropic" },
			},
			opts = {
				log_level = "TRACE",
			},
			adapters = {
				anthropic = function()
					return require("codecompanion.adapters").extend("anthropic", {
						schema = {
							model = {
								default = "claude-3-5-sonnet-20240620",
							},
							env = {
								api_key = "[redacted]",
							},
						},
					})
				end,
			},
		},
	},
}

require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

-- setup Tree-sitter
local ok, treesitter = pcall(require, "nvim-treesitter.configs")
if ok then
	treesitter.setup({
		ensure_installed = { "lua", "markdown", "markdown_inline" },
		highlight = { enable = true },
	})
end
```

### Error messages

```
[ERROR] 2024-08-26 11:32:06
Error: messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row
```

### Health check output

```
codecompanion: require("codecompanion.health").check()

codecompanion.nvim report ~
- Log file: /[redacted].repro/state/nvim/codecompanion.log
- OK plenary.nvim installed
- OK nvim-treesitter installed
- OK telescope.nvim installed
- OK dressing.nvim installed
- OK curl installed
```

### Log output

```
➜ cat ~/.local/state/nvim/codecompanion.log
[ERROR] 2024-08-26 11:14:27
Error: messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row
[ERROR] 2024-08-26 11:15:34
Error: messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row
[ERROR] 2024-08-26 11:16:03
Error: messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row
[ERROR] 2024-08-26 11:16:09
Error: messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row
[ERROR] 2024-08-26 11:16:49
Error: messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row
[ERROR] 2024-08-26 11:19:06
Error: messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row
[ERROR] 2024-08-26 11:23:37
Error: messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row
```

### Describe the bug

Since updating to [this](https://github.com/olimorris/codecompanion.nvim/commit/f248b7bff158ad296e54ffbcdbd17f4a57473d4e) commit I cannot use the Antropic adapter, especially in the Chat strategy when referencing the buffer with #buffer. It fails with the message: `Error: messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row`.

Seems related to [this](https://github.com/olimorris/codecompanion.nvim/commit/a01731f739085fc1d6d31fee1dd8409b6f88bcec) commit (but that is a very uneducated guess 😬 )

### Reproduce the bug

1. Set up Anthropic key and select anthropic adapter for the chat strategy
2. open a buffer that has some code/text
3. run `:CodeCompanionChat`
4. ask a question, starting with #buffer  and 💥 

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` file from above and have shared this
- [X] I have shared the contents of the log file

**Comment by olimorris** [comment]
Ahhhh great spot and thanks for raising. I was over zealous in my adapter refactor last night.

**Comment by olimorris** [comment]
This should now be fixed in the latest commit

**Comment by ivo-toby** [comment]
Thanks for fixing this so quickly! Works great!

**Comment by olimorris** [comment]
@ivo-toby i've just added prompt caching with Anthropic to the plugin. Would love to get your feedback and whether you notice token consumption reducing or any weird quirks/errors.

**Comment by ivo-toby** [comment]
Happy to try! But first I need to figure out why I'm not seeing any token usage in Anthropics dashboards. I've been using CodeCompanion for over a week with Claude but no usage has been registered (and I'm very certain I'm using the anthropic adapter)

**Comment by olimorris** [comment]
_quickly checks he hasn't hardcoded his API key into the plugin_

That's really odd. Your original issue was definitely an Anthropic one.

I notice their API times out when our US friends come online. So suspect there may be issues they're still ironing out.

**Comment by olimorris** [comment]
Ahhhhhh. Yes by default it will as per the adapter settings. You'd need to tell it where to look otherwise.

My personal preference is to use 1Password's CLI or GPG.

**Comment by ivo-toby** [comment]
Used it all day yesterday and compared to previous days it seems the token usage is roughly cut by 50%. And I used `#buffers` in chat quite a lot yesterday. (btw; that is really a killer feature, but I was wondering what happens if the buffers exceed the context-window)

Saw one occurrence in which is was reusing context from a previous chat in a new chat, but I have not been able to reproduce that yet, so can't pinpoint how that happened (may also be PEBCAK)
