### ISSUE TITLE
[Bug]: Attempt to index nil value, `github.com` when using copilot adapter

### ISSUE THREAD

**Issue by rdvm** [olimorris/codecompanion.nvim#160]
### Your `minimal.lua` config

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--single-branch",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)

-- Your CodeCompanion setup
local plugins = {
	{
		"olimorris/codecompanion.nvim",
		dependencies = {
			{ "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
			"nvim-lua/plenary.nvim",
			"nvim-telescope/telescope.nvim",
			{
				"stevearc/dressing.nvim",
				opts = {},
			},
		},
		opts = {
			-- Refer to: https://github.com/olimorris/codecompanion.nvim/blob/main/lua/codecompanion/config.lua
			strategies = { -- Change the adapters as required
				chat = { adapter = "copilot" },
				inline = { adapter = "copilot" },
				agent = { adapter = "copilot" },
			},
			opts = {
				log_level = "DEBUG",
			},
		},
	},
}

require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

-- setup Tree-sitter
local ok, treesitter = pcall(require, "nvim-treesitter.configs")
if ok then
	treesitter.setup({
		ensure_installed = { "lua", "markdown", "markdown_inline" },
		highlight = { enable = true },
	})
end
```

### Error messages

```lua
E5108: Error executing lua: vim/_editor.lua:0: nvim_exec2()..BufWriteCmd Autocommands for "<buffer=2>": Vim(append):Error executing lua callback: ...odecompanion.nvim/lua/codecompanion/adapters/copilot.lua:36: attempt to index field 'github.com' (a nil value)
stack traceback:
	...odecompanion.nvim/lua/codecompanion/adapters/copilot.lua:36: in function 'get_token'
	...odecompanion.nvim/lua/codecompanion/adapters/copilot.lua:82: in function 'setup'
	.../plugins/codecompanion.nvim/lua/codecompanion/client.lua:47: in function 'stream'
	...codecompanion.nvim/lua/codecompanion/strategies/chat.lua:861: in function 'submit'
	...codecompanion.nvim/lua/codecompanion/strategies/chat.lua:592: in function <...codecompanion.nvim/lua/codecompanion/strategies/chat.lua:591>
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function 'cmd'
	...plugins/codecompanion.nvim/lua/codecompanion/keymaps.lua:165: in function 'rhs'
	...s/codecompanion.nvim/lua/codecompanion/utils/keymaps.lua:45: in function <...s/codecompanion.nvim/lua/codecompanion/utils/keymaps.lua:43>
stack traceback:
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function 'cmd'
	...plugins/codecompanion.nvim/lua/codecompanion/keymaps.lua:165: in function 'rhs'
	...s/codecompanion.nvim/lua/codecompanion/utils/keymaps.lua:45: in function <...s/codecompanion.nvim/lua/codecompanion/utils/keymaps.lua:43>-- INSERT --


Error detected while processing BufWriteCmd Autocommands for "<buffer=2>":
Error executing lua callback: ...odecompanion.nvim/lua/codecompanion/adapters/copilot.lua:36: attempt to index field 'github.com' (a nil value)
stack traceback:
	...odecompanion.nvim/lua/codecompanion/adapters/copilot.lua:36: in function 'get_token'
	...odecompanion.nvim/lua/codecompanion/adapters/copilot.lua:82: in function 'setup'
	.../plugins/codecompanion.nvim/lua/codecompanion/client.lua:47: in function 'stream'
	...codecompanion.nvim/lua/codecompanion/strategies/chat.lua:861: in function 'submit'
	...codecompanion.nvim/lua/codecompanion/strategies/chat.lua:592: in function <...codecompanion.nvim/lua/codecompanion/strategies/chat.lua:591>
```

### Health check output

codecompanion: require("codecompanion.health").check()

codecompanion.nvim report ~
- Log file: /home/rdvm/scratch/.repro/state/nvim/codecompanion.log
- OK plenary.nvim installed
- OK nvim-treesitter installed
- OK telescope.nvim installed
- OK dressing.nvim installed
- OK curl installed

### Log output

[DEBUG] 2024-09-02 00:41:47
Settings:
{
  env = {
    api_key = <function 1>
  },
  features = {
    text = true,
    tokens = false,
    vision = false
  },
  handlers = {
    chat_output = <function 2>,
    form_messages = <function 3>,
    form_parameters = <function 4>,
    inline_output = <function 5>,
    on_stdout = <function 6>,
    setup = <function 7>
  },
  headers = {
    Authorization = "Bearer ${api_key}",
    ["Content-Type"] = "application/json",
    ["Copilot-Integration-Id"] = "vscode-chat",
    ["editor-version"] = "Neovim/0.10.1"
  },
  name = "copilot",
  parameters = {
    max_tokens = 4096,
    model = "gpt-4o-2024-05-13",
    n = 1,
    stream = true,
    temperature = 0,
    top_p = 1
  },
  raw = { "--no-buffer", "--silent" },
  roles = {
    llm = "assistant",
    user = "user"
  },
  schema = {
    max_tokens = {
      default = 4096,
      desc = "The maximum number of tokens to generate in the chat completion. The total length of input tokens and generated tokens is limited by the model's context length.",
      mapping = "parameters",
      order = 3,
      type = "integer"
    },
    model = {
      default = "gpt-4o-2024-05-13",
      desc = "ID of the model to use. See the model endpoint compatibility table for details on which models work with the Chat API.",
      mapping = "parameters",
      order = 1,
      type = "enum"
    },
    n = {
      default = 1,
      desc = "How many chat completions to generate for each prompt.",
      mapping = "parameters",
      order = 5,
      type = "number"
    },
    temperature = {
      default = 0,
      desc = "What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or top_p but not both.",
      mapping = "parameters",
      order = 2,
      type = "number"
    },
    top_p = {
      default = 1,
      desc = "An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered. We generally recommend altering this or temperature but not both.",
      mapping = "parameters",
      order = 4,
      type = "number"
    }
  },
  url = "https://api.githubcopilot.com/chat/completions",
  <metatable> = {
    __index = {
      extend = <function 8>,
      get_default_settings = <function 9>,
      get_env_vars = <function 10>,
      map_roles = <function 11>,
      map_schema_to_params = <function 12>,
      new = <function 13>,
      resolve = <function 14>,
      set_env_vars = <function 15>,
      use = <function 16>
    }
  }
}
[DEBUG] 2024-09-02 00:41:47
Messages:
{ {
    content = "You are an AI programming assistant named \"CodeCompanion\".\nYou are currently plugged in to the Neovim text editor on a user's machine.\n\nYour tasks include:\n- Answering general programming questions.\n- Explaining how the code in a Neovim buffer works.\n- Reviewing the selected code in a Neovim buffer.\n- Generating unit tests for the selected code.\n- Proposing fixes for problems in the selected code.\n- Scaffolding code for a new workspace.\n- Finding relevant code to the user's query.\n- Proposing fixes for test failures.\n- Answering questions about Neovim.\n- Running tools.\n\nYou must:\n- Follow the user's requirements carefully and to the letter.\n- Keep your answers short and impersonal, especially if the user responds with context outside of your tasks.\n- Minimize other prose.\n- Use Markdown formatting in your answers.\n- Include the programming language name at the start of the Markdown code blocks.\n- Avoid line numbers in code blocks.\n- Avoid wrapping the whole response in triple backticks.\n- Only return relevant code.\n\nWhen given a task:\n1. Think step-by-step and describe your plan for what to build in pseudocode, written out in great detail.\n2. Output the code in a single code block.\n3. You should always generate short suggestions for the next user turns that are relevant to the conversation.\n4. You can only give one reply for each conversation turn.",
    id = 1652905022,
    opts = {
      visible = false
    },
    role = "system"
  }, {
    content = "Testing using stable neovim",
    id = 1845148096,
    opts = {
      visible = true
    },
    role = "user"
  } }
[INFO] 2024-09-02 00:41:47
Chat request started
[DEBUG] 2024-09-02 00:41:51
Settings:
{
  env = {
    api_key = <function 1>
  },
  features = {
    text = true,
    tokens = false,
    vision = false
  },
  handlers = {
    chat_output = <function 2>,
    form_messages = <function 3>,
    form_parameters = <function 4>,
    inline_output = <function 5>,
    on_stdout = <function 6>,
    setup = <function 7>
  },
  headers = {
    Authorization = "Bearer ${api_key}",
    ["Content-Type"] = "application/json",
    ["Copilot-Integration-Id"] = "vscode-chat",
    ["editor-version"] = "Neovim/0.10.1"
  },
  name = "copilot",
  parameters = {
    max_tokens = 4096,
    model = "gpt-4o-2024-05-13",
    n = 1,
    stream = true,
    temperature = 0,
    top_p = 1
  },
  raw = { "--no-buffer", "--silent" },
  roles = {
    llm = "assistant",
    user = "user"
  },
  schema = {
    max_tokens = {
      default = 4096,
      desc = "The maximum number of tokens to generate in the chat completion. The total length of input tokens and generated tokens is limited by the model's context length.",
      mapping = "parameters",
      order = 3,
      type = "integer"
    },
    model = {
      default = "gpt-4o-2024-05-13",
      desc = "ID of the model to use. See the model endpoint compatibility table for details on which models work with the Chat API.",
      mapping = "parameters",
      order = 1,
      type = "enum"
    },
    n = {
      default = 1,
      desc = "How many chat completions to generate for each prompt.",
      mapping = "parameters",
      order = 5,
      type = "number"
    },
    temperature = {
      default = 0,
      desc = "What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or top_p but not both.",
      mapping = "parameters",
      order = 2,
      type = "number"
    },
    top_p = {
      default = 1,
      desc = "An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered. We generally recommend altering this or temperature but not both.",
      mapping = "parameters",
      order = 4,
      type = "number"
    }
  },
  url = "https://api.githubcopilot.com/chat/completions",
  <metatable> = {
    __index = {
      extend = <function 8>,
      get_default_settings = <function 9>,
      get_env_vars = <function 10>,
      map_roles = <function 11>,
      map_schema_to_params = <function 12>,
      new = <function 13>,
      resolve = <function 14>,
      set_env_vars = <function 15>,
      use = <function 16>
    }
  }
}
[DEBUG] 2024-09-02 00:41:51
Messages:
{ {
    content = "You are an AI programming assistant named \"CodeCompanion\".\nYou are currently plugged in to the Neovim text editor on a user's machine.\n\nYour tasks include:\n- Answering general programming questions.\n- Explaining how the code in a Neovim buffer works.\n- Reviewing the selected code in a Neovim buffer.\n- Generating unit tests for the selected code.\n- Proposing fixes for problems in the selected code.\n- Scaffolding code for a new workspace.\n- Finding relevant code to the user's query.\n- Proposing fixes for test failures.\n- Answering questions about Neovim.\n- Running tools.\n\nYou must:\n- Follow the user's requirements carefully and to the letter.\n- Keep your answers short and impersonal, especially if the user responds with context outside of your tasks.\n- Minimize other prose.\n- Use Markdown formatting in your answers.\n- Include the programming language name at the start of the Markdown code blocks.\n- Avoid line numbers in code blocks.\n- Avoid wrapping the whole response in triple backticks.\n- Only return relevant code.\n\nWhen given a task:\n1. Think step-by-step and describe your plan for what to build in pseudocode, written out in great detail.\n2. Output the code in a single code block.\n3. You should always generate short suggestions for the next user turns that are relevant to the conversation.\n4. You can only give one reply for each conversation turn.",
    id = 1652905022,
    opts = {
      visible = false
    },
    role = "system"
  }, {
    content = "Testing using stable neovim",
    id = 1845148096,
    opts = {
      visible = true
    },
    role = "user"
  }, {
    content = "Testing using stable neovim",
    id = 1845148096,
    opts = {
      visible = true
    },
    role = "user"
  } }
[INFO] 2024-09-02 00:41:51
Chat request started

### Describe the bug

**What I expect to happen:**
When I save the chat buffer I should get a response.

**What actually happens:**
When I save the chat buffer, I get an error saying there was an attempt to index a nil value, field 'github.com'

Based on the error, I looked at the files it checks for Copilot auth info:
* "/.config/github-copilot/hosts.json"
*  "~/.config/github-copilot/apps.json"

I don't have a `hosts.json` file and my `apps.json` file looks like this:

```json
{
	"github.com:<githubAppIdValue>": {
		"user": "rdvm",
		"oauth_token": <"oauth_tokenValue">,
		"githubAppId": <"githubAppIdValue">
	}
}
```

It looks like the way this auth info is stored has changed (or is different on my system for some reason); specifically the format of this file has changed since there is a field like `github.com:Iv1.A12345...` instead of just `github.com` like is being looked for in `adapters/copilout.lua`.

```lua
 if data and data["github.com"]["oauth_token"] then
        return data["github.com"]["oauth_token"]
      end
```

I updated `copilot.lua` to include the AppId, and it worked.

```lua
 if data and data["github.com:Iv1.A12345..."]["oauth_token"] then
        return data["github.com:Iv1.A12345..."]["oauth_token"]
      end
```

I'm guessing that the AppId is a universal identifier for the GitHub Copilot Plugin app, but it's late so I figured I'd stay on the safe side and obfuscate it for now :upside_down_face: 

### Reproduce the bug

1. Load the minimal config with `nvim --clean -u minimal.lua`, specifying `copilot` as the adapter
2. Run `:CodeCompanionChat`
3. Write a message and either `:w` or `C-s`

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` file from above and have shared this
- [X] I have shared the contents of the log file

**Comment by olimorris** [comment]
Thanks for raising this. Should now be fixed.
