### ISSUE TITLE
Update Deprecated Functions

### ISSUE THREAD

**Issue by S1M0N38** [olimorris/codecompanion.nvim#194]
### Your `minimal.lua` config

.

### Log output

.

### Describe the bug

From the Neovim documentation (`doc/deprecated.txt`):

```
DEPRECATED IN 0.10 *deprecated-0.10*
...
• |API| functions:
  - ...
  - *nvim_buf_set_option()*   Use |nvim_set_option_value()| instead.
  - ...

• Lua stdlib:
  - ...
  - *vim.tbl_islist()*   Use |vim.islist()| instead.
```

These two deprecated functions are currently used in the `codecompanion.nvim` codebase. To ensure compatibility with future versions of Neovim, it would be best to update to the suggested alternatives.

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` file from above and have shared this
- [X] I have shared the contents of the log file

**Comment by olimorris** [comment]
Btw...did you get any notifications about the `nvim_buf_set_option()` deprecation? I somehow missed it.

**Comment by S1M0N38** [comment]
Yes

<img width="742" alt="Screenshot 2024-09-10 at 19 43 35" src="https://github.com/user-attachments/assets/60c57c53-a4bf-44ab-940c-fd34f43cc75b">

I'm using LazyVim. It make use of [lazydev.nvim](https://github.com/folke/lazydev.nvim). I'm not sure but I think that these LSP diagnostic are from LuaLS set up by lazydev
