### ISSUE TITLE
[Bug]: fzf-lua dependency

### ISSUE THREAD

**Issue by Konfekt** [olimorris/codecompanion.nvim#213]
### Your `minimal.lua` config

.

### Error messages

.

### Log output

.

### Health check output

.

### Describe the bug

The FZF window that opens after entering `:CodeCompanionActions<cr>` is unreadably even with fullscreen vim. 

If https://github.com/ibhagwan/fzf-lua is installed, then it becomes readable in fullscreen, but still unreadable 

![grafik](https://github.com/user-attachments/assets/a0125a59-1826-4f76-8eca-cc1581704562)

if, say, the columwidth is, say, below 100 as shown below

Instead, ensure that the first column is always show and rather shorten the rightmost.

So the first step would be to add https://github.com/ibhagwan/fzf-lua as a dependency (which can optionally be replaced by telescope), and then ensure that at least the leftmost columns stays readable.

### Reproduce the bug

Enter `:CodeCompanionActions<cr>`.

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` file from above and have shared this
- [X] I have shared the contents of the log file

**Comment by olimorris** [comment]
Please provide the `minimal.lua` file so that I can test this.

**Comment by Konfekt** [comment]
```lua
call plug#begin()

Plug "nvim-lua/plenary.nvim"
Plug "nvim-treesitter/nvim-treesitter"
Plug "nvim-telescope/telescope.nvim", " Optional: For using slash commands
Plug "olimorris/codecompanion.nvim"

call plug#end()

lua << EOF
  require("codecompanion").setup()
EOF
```

**Comment by Konfekt** [comment]
This is with Neovim

```
NVIM v0.11.0-dev-684+g53af02adb
Build type: RelWithDebInfo
LuaJIT 2.1.1724512491
```

**Comment by olimorris** [comment]
Please create a new issue following the minimal.lua file I've provided in the bug report.
