### ISSUE TITLE
[Bug]: Copilot request without stream are not parsed

### ISSUE THREAD

**Issue by lucobellic** [olimorris/codecompanion.nvim#261]
While working with copilot to enable the use of the o1 model (require stream set to false), I realized that the requests were not being parsed.

### Your `minimal.lua` config

```lua
{
  'olimorris/codecompanion.nvim',
  opts = {
    adapters = {
      copilot = function()
        return require('codecompanion.adapters').extend('copilot', {
          parameters = {
            stream = false,
          },
        })
      end,
    },
    strategies = {
      chat = {
        adapter = 'copilot',
      },
    },
  },
},
```

### Log output

[DEBUG] 2024-09-27 00:06:48
Messages:
{ {
    content = "You are an AI programming assistant named \"CodeCompanion\".\nYou are currently plugged in to the Neovim text editor on a user's machine.\n\nYour core tasks include:\n- Answering general programming questions.\n- Explaining how the code in a Neovim buffer works.\n- Reviewing the selected code in a Neovim buffer.\n- Generating unit tests for the selected code.\n- Proposing fixes for problems in the selected code.\n- Scaffolding code for a new workspace.\n- Finding relevant code to the user's query.\n- Proposing fixes for test failures.\n- Answering questions about Neovim.\n- Running tools.\n\nYou must:\n- Follow the user's requirements carefully and to the letter.\n- Keep your answers short and impersonal, especially if the user responds with context outside of your tasks.\n- Minimize other prose.\n- Use Markdown formatting in your answers.\n- Include the programming language name at the start of the Markdown code blocks.\n- Avoid line numbers in code blocks.\n- Avoid wrapping the whole response in triple backticks.\n- Only return relevant code.\n\nWhen given a task:\n1. Think step-by-step and describe your plan for what to build in pseudocode, written out in great detail.\n2. Output the code in a single code block, being careful to only return relevant code.\n3. You should always generate short suggestions for the next user turns that are relevant to the conversation.\n4. You can only give one reply for each conversation turn.",
    id = -1651938196,
    opts = {
      visible = false
    },
    role = "system"
  }, {
    content = "Say hello",
    id = 1012489819,
    opts = {
      visible = true
    },
    role = "user"
  } }
[INFO] 2024-09-27 00:06:48
Chat request started
[DEBUG] 2024-09-27 00:06:48
Authorizing GitHub Copilot token
[DEBUG] 2024-09-27 00:06:49
Reusing GitHub Copilot token
[DEBUG] 2024-09-27 00:06:49
Request:
{ "-sSL", "-D", "/run/user/1000/plenary_curl_b0b741c4.headers", "--compressed", "-X", "POST", "-H", "Content-Type: application/json", "-H", "Copilot-Integration-Id: vscode-chat", "-H", "Editor-Version: Neovim/0.10.1", "-H", "Authorization: Bearer tid=...;exp=...;sku=...;st=dotcom;chat=1;cit=1;8kp=1;ip=....;asn=...", "--data-raw", "{\"messages\":[{\"content\":\"You are an AI programming assistant named \\\"CodeCompanion\\\".\\nYou are currently plugged in to the Neovim text editor on a user's machine.\\n\\nYour core tasks include:\\n- Answering general programming questions.\\n- Explaining how the code in a Neovim buffer works.\\n- Reviewing the selected code in a Neovim buffer.\\n- Generating unit tests for the selected code.\\n- Proposing fixes for problems in the selected code.\\n- Scaffolding code for a new workspace.\\n- Finding relevant code to the user's query.\\n- Proposing fixes for test failures.\\n- Answering questions about Neovim.\\n- Running tools.\\n\\nYou must:\\n- Follow the user's requirements carefully and to the letter.\\n- Keep your answers short and impersonal, especially if the user responds with context outside of your tasks.\\n- Minimize other prose.\\n- Use Markdown formatting in your answers.\\n- Include the programming language name at the start of the Markdown code blocks.\\n- Avoid line numbers in code blocks.\\n- Avoid wrapping the whole response in triple backticks.\\n- Only return relevant code.\\n\\nWhen given a task:\\n1. Think step-by-step and describe your plan for what to build in pseudocode, written out in great detail.\\n2. Output the code in a single code block, being careful to only return relevant code.\\n3. You should always generate short suggestions for the next user turns that are relevant to the conversation.\\n4. You can only give one reply for each conversation turn.\",\"role\":\"system\",\"id\":-1651938196,\"opts\":{\"visible\":false}},{\"content\":\"Say hello\",\"role\":\"user\",\"id\":....,\"opts\":{\"visible\":true}}],\"max_tokens\":4096,\"model\":\"gpt-4o-2024-05-13\",\"temperature\":0,\"stream\":false,\"top_p\":1,\"n\":1}", "--no-buffer", "--silent", "https://api.githubcopilot.com/chat/completions" }
[TRACE] 2024-09-27 00:06:50
Request data:
{"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"protected_material_code":{"detected":false,"filtered":false},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"finish_reason":"stop","index":0,"message":{"content":"Hello! How can I assist you with your programming tasks today?","role":"assistant"}}],"created":1727388409,"id":"chatcmpl-","model":"gpt-4o-2024-05-13","prompt_filter_results":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"prompt_index":0}],"system_fingerprint":".......","usage":{"completion_tokens":13,"prompt_tokens":311,"total_tokens":324}}
[TRACE] 2024-09-27 00:06:50
stdout: {
  choices = { {
      content_filter_results = {
        hate = {
          filtered = false,
          severity = "safe"
        },
        protected_material_code = {
          detected = false,
          filtered = false
        },
        self_harm = {
          filtered = false,
          severity = "safe"
        },
        sexual = {
          filtered = false,
          severity = "safe"
        },
        violence = {
          filtered = false,
          severity = "safe"
        }
      },
      finish_reason = "stop",
      index = 0,
      message = {
        content = "Hello! How can I assist you with your programming tasks today?",
        role = "assistant"
      }
    } },
  created = 1727388409,
  id = "chatcmpl-......",
  model = "gpt-4o-2024-05-13",
  prompt_filter_results = { {
      content_filter_results = {
        hate = {
          filtered = false,
          severity = "safe"
        },
        self_harm = {
          filtered = false,
          severity = "safe"
        },
        sexual = {
          filtered = false,
          severity = "safe"
        },
        violence = {
          filtered = false,
          severity = "safe"
        }
      },
      prompt_index = 0
    } },
  system_fingerprint = "fp_......",
  usage = {
    completion_tokens = 13,
    prompt_tokens = 311,
    total_tokens = 324
  }
}
[INFO] 2024-09-27 00:06:50
Chat request completed

### Describe the bug

What I expect to happen:
Text appear in the chat

What actually happens:
Nothing

### Reproduce the bug

Steps to reproduce:
1. Use the minimal configuration with copilot and stream parameter set to `false`
2. Ask something in the chat

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` file from above and have shared this
- [X] I have shared the contents of the log file

**Comment by olimorris** [comment]
Yep that's to be expected. If you look at `http.lua` you'll see we stream everything.
