### ISSUE TITLE
[Bug]: Inline index nil prompts table

### ISSUE THREAD

**Issue by SDGLBL** [olimorris/codecompanion.nvim#274]
### Your `minimal.lua` config

```lua
---@diagnostic disable: missing-fields

--NOTE: Set config path to enable the copilot adapter to work.
--It will search the follwoing paths for the for copilot token:
--  - "$CODECOMPANION_TOKEN_PATH/github-copilot/hosts.json"
--  - "$CODECOMPANION_TOKEN_PATH/github-copilot/apps.json"
vim.env["CODECOMPANION_TOKEN_PATH"] = vim.fn.expand("~/.config")

vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

-- Your CodeCompanion setup
local plugins = {
  {
    "olimorris/codecompanion.nvim",
    dependencies = {
      { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
      { "nvim-lua/plenary.nvim" },
      { "hrsh7th/nvim-cmp" },
      { "stevearc/dressing.nvim", opts = {} },
      { "nvim-telescope/telescope.nvim" },
    },
    opts = {
      --Refer to: https://github.com/olimorris/codecompanion.nvim/blob/main/lua/codecompanion/config.lua
      strategies = {
        --NOTE: Change the adapter as required
        chat = { adapter = "openai" },
        inline = { adapter = "openai" },
        agent = { adapter = "openai" },
      },
      prompt_library = {
          ["Write"] ={
  name = "Write",
  strategy = "inline",
  description = "Write doc/comments/commit message",
  opts = {
    index = 2,
    modes = { "n", "v" },
  },
  picker = {
    prompt = "Write",
    items = function()
      local select_items = {}
      table.insert(select_items, prompts.write_in_context)
      table.insert(select_items, prompts.write_comment)
      table.insert(select_items, prompts.write_git_message)
      return select_items
    end,
  },
},
        },
      opts = {
        log_level = "DEBUG",
      },
    },
  },
}

require("lazy.minit").repro({ spec = plugins })

-- Setup Tree-sitter
local ts_status, treesitter = pcall(require, "nvim-treesitter.configs")
if ts_status then
  treesitter.setup({
    ensure_installed = { "lua", "markdown", "markdown_inline", "yaml" },
    highlight = { enable = true },
  })
end

-- Setup completion
local cmp_status, cmp = pcall(require, "cmp")
if cmp_status then
  cmp.setup({
    mapping = cmp.mapping.preset.insert({
      ["<C-b>"] = cmp.mapping.scroll_docs(-4),
      ["<C-f>"] = cmp.mapping.scroll_docs(4),
      ["<C-Space>"] = cmp.mapping.complete(),
      ["<C-e>"] = cmp.mapping.abort(),
      ["<CR>"] = cmp.mapping.confirm({ select = true }),
      -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
    }),
  })
end
```

### Error messages

Error executing vim.schedule lua callback: ...decompanion.nvim/lua/codecompanion/strategies/inline.lua:404: bad argument #1 to 'ipairs' (table expe
cted, got nil)
stack traceback:
        [C]: in function 'ipairs'
        ...decompanion.nvim/lua/codecompanion/strategies/inline.lua:404: in function 'form_prompt'
        ...decompanion.nvim/lua/codecompanion/strategies/inline.lua:226: in function 'cb'
        ...ocal/share/nvim/lazy/dressing.nvim/lua/dressing/util.lua:206: in function <...ocal/share/nvim/lazy/dressing.nvim/lua/dressing/util.lua:2
02>

### Log output

```text
```

### Describe the bug

Failed to parse the picker field in the custom prompt

Error executing vim.schedule lua callback: ...decompanion.nvim/lua/codecompanion/strategies/inline.lua:404: bad argument #1 to 'ipairs' (table expe
cted, got nil)
stack traceback:
        [C]: in function 'ipairs'
        ...decompanion.nvim/lua/codecompanion/strategies/inline.lua:404: in function 'form_prompt'
        ...decompanion.nvim/lua/codecompanion/strategies/inline.lua:226: in function 'cb'
        ...ocal/share/nvim/lazy/dressing.nvim/lua/dressing/util.lua:206: in function <...ocal/share/nvim/lazy/dressing.nvim/lua/dressing/util.lua:2
02>

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` file from above and have shared this
- [X] I have shared the contents of the log file

**Comment by olimorris** [comment]
Thank you for this and for the detailed report outlining how to use this.
