### ISSUE TITLE
API configuration

### ISSUE THREAD

**Issue by mrjones2014** [olimorris/codecompanion.nvim#3]
Hey just seeing this, looks very cool! It would be cool to be able to use LocalAI, since OpenAI API is quite expensive. LocalAI has a drop-in replacement REST API, so (if things work out the way I hope) it should just be a matter of setting the base URL and all the API endpoint mappings and request/response logic should still work.

https://github.com/mudler/LocalAI

**Comment by olimorris** [comment]
I will look into this at some point in the future. Haven't had time to setup LocalAI and models yet.

**Comment by gitaarik** [comment]
Did anyone get this to work yet?

**Comment by olimorris** [comment]
@gitaarik check out https://github.com/olimorris/codecompanion.nvim/blob/main/doc/ADAPTERS.md. Adapters were added after this discussion.
