### ISSUE TITLE
[Bug]: Slash commands do not add anything to Chat

### ISSUE THREAD

**Issue by michaelmichael** [olimorris/codecompanion.nvim#311]
### Your `minimal.lua` config

```lua
---@diagnostic disable: missing-fields

--NOTE: Set config path to enable the copilot adapter to work.
--It will search the follwoing paths for the for copilot token:
--  - "$CODECOMPANION_TOKEN_PATH/github-copilot/hosts.json"
--  - "$CODECOMPANION_TOKEN_PATH/github-copilot/apps.json"
vim.env["CODECOMPANION_TOKEN_PATH"] = vim.fn.expand("~/.config")

vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

-- Your CodeCompanion setup
local plugins = {
  {
    "olimorris/codecompanion.nvim",
    dependencies = {
      { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
      { "nvim-lua/plenary.nvim" },
      { "hrsh7th/nvim-cmp" },
      { "stevearc/dressing.nvim", opts = {} },
      { "nvim-telescope/telescope.nvim" },
    },
    opts = {
      --Refer to: https://github.com/olimorris/codecompanion.nvim/blob/main/lua/codecompanion/config.lua
      strategies = {
        --NOTE: Change the adapter as required
        chat = { adapter = "copilot" },
        inline = { adapter = "copilot" },
      },
      opts = {
        log_level = "DEBUG",
      },
    },
  },
}

require("lazy.minit").repro({ spec = plugins })

-- Setup Tree-sitter
local ts_status, treesitter = pcall(require, "nvim-treesitter.configs")
if ts_status then
  treesitter.setup({
    ensure_installed = { "lua", "markdown", "markdown_inline", "yaml" },
    highlight = { enable = true },
  })
end

-- Setup completion
local cmp_status, cmp = pcall(require, "cmp")
if cmp_status then
  cmp.setup({
    mapping = cmp.mapping.preset.insert({
      ["<C-b>"] = cmp.mapping.scroll_docs(-4),
      ["<C-f>"] = cmp.mapping.scroll_docs(4),
      ["<C-Space>"] = cmp.mapping.complete(),
      ["<C-e>"] = cmp.mapping.abort(),
      ["<CR>"] = cmp.mapping.confirm({ select = true }),
      -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
    }),
  })
end
```

### Error messages

```text
[WARN] 2024-10-10 13:20:38
No messages to submit
```

### Log output

```txt
[DEBUG] 2024-10-10 13:11:12
Executing slash command: file
[DEBUG] 2024-10-10 13:11:12
Calling slash command: helpers.slash_commands.file
[DEBUG] 2024-10-10 13:13:28
Executing slash command: file
[DEBUG] 2024-10-10 13:13:28
Calling slash command: helpers.slash_commands.file
[WARN] 2024-10-10 13:13:33
No messages to submit
[DEBUG] 2024-10-10 13:20:33
Executing slash command: file
[DEBUG] 2024-10-10 13:20:33
Calling slash command: helpers.slash_commands.file
[WARN] 2024-10-10 13:24:08
No messages to submit
```

### Health check output

```txt
﻿﻿﻿﻿﻿﻿﻿﻿﻿──────────────────────────────────────────────────────────────────────────────
codecompanion: require("codecompanion.health").check()

- Neovim version: 0.10.1
- Log file: /Users/michaelcaviness/code/tcw-frontend/.repro/state/nvim/codecompanion.log

Plugins:
- OK plenary.nvim installed
- OK nvim-treesitter installed
- OK nvim-cmp installed
- OK telescope.nvim installed
- OK dressing.nvim installed

Tree-sitter parsers:
- OK markdown parser installed
- OK yaml parser installed

Libraries:
- OK curl installed
```

## What I expect to happen:
I expect the contents of a file to be added to the CodeCompanion Chat buffer when using the `/file` slash command.
## What actually happens:
Nothing is inserted into the chat buffer. If I try to submit the contents of the buffer after selecting a file with `/file` it will return the aforementioned error indicating that nothing was submitted. 

It seems like this was introduced in `dba83b9c632d099a6f8acc3cc178f7b51156750f`. If I pin CodeCompanion.nvim to the previous commit, `54b310779fd5c2597a21a0c146080a8adfa608b7`, it works as it previously did. 

The next commit's message is `feat: slash command output is now hidden`, so if this was intentional and I'm just not used to the new workflow, or doing something wrong, I apologize.

### Reproduce the bug

1. Open `:CodeCompanionChat`
2. Enter the `/file` slash command
3. Pick a file from the telescope window
4. Press enter
5. Try to submit the chat.

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` file from above and have shared this
- [X] I have shared the contents of the log file

**Comment by olimorris** [comment]
Hey @michaelmichael. This is now by design...all except for the `now` slash command. You should be getting a notification that it's been added though to the chat buffer though. Is that visible?

**Comment by michaelmichael** [comment]
Thanks! I am getting that message. As noted, though, if there's nothing else in the buffer then trying to submit fails with the "No messages to submit" error. Previously if you ran the `/file` slash command and included no further content, you would get a response from the LLM agent saying something to the effect of "This file is a ______ that does ______". 

If this new say is by design, cool. No issues, and I'll get used to a different workflow. Closing for now, and much appreciated!

**Comment by olimorris** [comment]
Ooooh that's a very good spot. I had never considered that workflow. Right, I've accounted for this in `v8.3.1`.

**Comment by psakalo** [comment]
@olimorris just wondering what was the reason for reworking this functionality? I actually came here looking after encountered similar issue, and for me, new approach is kinda confusing. I really liked how codecompanion among other alternatives clearly exposed context in a form of chat text buffer. It was pretty useful to be able to see and edit all included context. Is there currently a way to see/edit context attached to a buffer via slash commands?

**Comment by olimorris** [comment]
@psakalo I put it to a poll a couple of weeks ago in https://github.com/olimorris/codecompanion.nvim/discussions/309.

Long and the short of it; I was finding that folds in the chat buffer were unreliable especially when combining markdown content being inserted into the markdown buffer.

You can still see the contents of the message block with `gd`.

**Comment by psakalo** [comment]
got it @olimorris! Seems reasonable to me, although I would just plant an idea to still somehow surface a fact something is attached in the chat buffer. I don't use any notification plugin, and for me it's just a small text at the bottom of the screen popping up. It's very easy to miss, and IMO would cause more confusion. 

Also, it would be nice to understand if you have anything attached while getting back to the chat buffer. I don't know if this is possible in the current implementation, but perhaps a `## Me -----` header might be an option here, something like `## Me (context: foo) ---`.
