### ISSUE TITLE
[Bug]: `@editor` tool does not escape XML characters like `>`

### ISSUE THREAD

**Issue by GordianDziwis** [olimorris/codecompanion.nvim#336]
### Your `minimal.lua` config

```lua
```

### Log output

```txt
```

### Describe the bug

The `@editor` tool fails to produce parsable XML, when special XML chars are inside the code.

```xml
<tools>
  <tool name="editor">
    <action type="update">
      <code>
fn has_parent_matching<F>( // This won't get parsed because of <F> 
...
}</code>
      <start_line>17</start_line>
      <end_line>37</end_line>
      <buffer>8</buffer>
    </action>
  </tool>
</tools>
```

### Reproduce the bug

You could update the schema and wrap the code content in a CDATA section. This tells the XML parser to treat the content as character data, not markup. Here's how you can do that:

```xml
<tools>
  <tool name="editor">
    <action type="update">
      <code><![CDATA[
fn has_parent_matching<F>( // This won't get parsed because 
...
}]]></code>
      <start_line>17</start_line>
      <end_line>37</end_line>
      <buffer>8</buffer>
    </action>
  </tool>
</tools>
```

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` file from above and have shared this
- [X] I have shared the contents of the log file

**Comment by olimorris** [comment]
Oooof good spot. Can you submit a PR for this? You could just amend the system prompt in the editor tool for the LLM to follow.
