### ISSUE TITLE
[Bug]: Unable to see included files in the chat panel

### ISSUE THREAD

**Issue by roguesherlock** [olimorris/codecompanion.nvim#395]
### Your `minimal.lua` config

```lua
---@diagnostic disable: missing-fields

--NOTE: Set config path to enable the copilot adapter to work.
--It will search the follwoing paths for the for copilot token:
--  - "$CODECOMPANION_TOKEN_PATH/github-copilot/hosts.json"
--  - "$CODECOMPANION_TOKEN_PATH/github-copilot/apps.json"
vim.env["CODECOMPANION_TOKEN_PATH"] = vim.fn.expand("~/.config")

vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

-- Your CodeCompanion setup
local plugins = {
  {
    "olimorris/codecompanion.nvim",
    dependencies = {
      { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
      { "nvim-lua/plenary.nvim" },
      { "hrsh7th/nvim-cmp" },
      { "stevearc/dressing.nvim", opts = {} },
      { "nvim-telescope/telescope.nvim" },
    },
    opts = {
      --Refer to: https://github.com/olimorris/codecompanion.nvim/blob/main/lua/codecompanion/config.lua
      strategies = {
        --NOTE: Change the adapter as required
        chat = { adapter = "copilot" },
        inline = { adapter = "copilot" },
      },
      opts = {
        log_level = "DEBUG",
      },
    },
  },
}

require("lazy.minit").repro({ spec = plugins })

-- Setup Tree-sitter
local ts_status, treesitter = pcall(require, "nvim-treesitter.configs")
if ts_status then
  treesitter.setup({
    ensure_installed = { "lua", "markdown", "markdown_inline", "yaml" },
    highlight = { enable = true },
  })
end

-- Setup completion
local cmp_status, cmp = pcall(require, "cmp")
if cmp_status then
  cmp.setup({
    mapping = cmp.mapping.preset.insert({
      ["<C-b>"] = cmp.mapping.scroll_docs(-4),
      ["<C-f>"] = cmp.mapping.scroll_docs(4),
      ["<C-Space>"] = cmp.mapping.complete(),
      ["<C-e>"] = cmp.mapping.abort(),
      ["<CR>"] = cmp.mapping.confirm({ select = true }),
      -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
    }),
  })
end
```

### Error messages

no error messages 

### Log output

no errors

### Health check output

```
codecompanion: require("codecompanion.health").check()

- Neovim version: 0.10.2
- Log file: /Users/akash/.local/state/nvim/codecompanion.log

Plugins: ~
- OK plenary.nvim installed
- OK nvim-treesitter installed
- OK nvim-cmp installed
- WARNING telescope.nvim not found
- OK dressing.nvim installed

Tree-sitter parsers: ~
- OK markdown parser installed
- OK yaml parser installed

Libraries: ~
- OK curl installed
```

### Describe the bug

Unable to see included files in the chat panel

https://github.com/user-attachments/assets/6a0b1521-3a16-4361-a2e3-771c935bfe95

### Reproduce the bug

- Open chat panel
- Use /file command to include file

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` file from above and have shared this
- [X] I have shared the contents of the log file

**Comment by roguesherlock** [comment]
hey thanks for building this, I really like it.

I wasn't sure if it's a bug or it just doesn't support but I think I used to be able to see the included files in the chat panel before.

btw I also tried it with the minimal config you had in the bug template and still wasn't able to see the files in the chat panel.

I'm using following neovim version but let me know how can I help you debug this further.
```
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382
```

**Comment by olimorris** [comment]
Glad you're enjoying it.

All slash commands send a `vim.notify` call which outputs that a file has been added to the chat buffer. However, if your cmdline is set to zero, you may not see it. As a fallback, you can do `gd` to see the message stack but that's a lot of code to wade through.

A few user's have raised this recently so I will definitely look to address this in the near future.

I'll close for now but feel free to open up a discussion to talk about how we could resolve this.

**Comment by roguesherlock** [comment]
> Glad you're enjoying it.
> 
> All slash commands send a `vim.notify` call which outputs that a file has been added to the chat buffer. However, if your cmdline is set to zero, you may not see it. As a fallback, you can do `gd` to see the message stack but that's a lot of code to wade through.
> 
> A few user's have raised this recently so I will definitely look to address this in the near future.
> 
> I'll close for now but feel free to open up a discussion to talk about how we could add this feature.

Thanks! I do get the notification, but I swear I was able to see the linked files in the markdown chat panel itself, is that not the case? 
Maybe I am just remember what zed does. In this case, should we add that functionality in?
Lot of the times I add multiple files in the buffer, and it'd be nice to see them being linked in the chat panel itself, does it make sense?
