### ISSUE TITLE
[Bug]: `CodeCompanionChat Toggle` with `layout = "buffer"` breaks with split windows

### ISSUE THREAD

**Issue by GordianDziwis** [olimorris/codecompanion.nvim#402]
### Your `minimal.lua` config

```lua
---@diagnostic disable: missing-fields

--NOTE: Set config path to enable the copilot adapter to work.
--It will search the follwoing paths for the for copilot token:
--  - "$CODECOMPANION_TOKEN_PATH/github-copilot/hosts.json"
--  - "$CODECOMPANION_TOKEN_PATH/github-copilot/apps.json"
vim.env["CODECOMPANION_TOKEN_PATH"] = vim.fn.expand("~/.config")

vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

-- Your CodeCompanion setup
local plugins = {
    {
        "olimorris/codecompanion.nvim",
        dependencies = {
            { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
            { "nvim-lua/plenary.nvim" },
            { "hrsh7th/nvim-cmp" },
            { "stevearc/dressing.nvim",          opts = {} },
            { "nvim-telescope/telescope.nvim" },
        },
        opts = {
            --Refer to: https://github.com/olimorris/codecompanion.nvim/blob/main/lua/codecompanion/config.lua
            strategies = {
                --NOTE: Change the adapter as required
                chat = { adapter = "copilot" },

                inline = { adapter = "copilot" },
            },
            display = {
                chat = {
                    window = {
                        layout = "buffer", -- float|vertical|horizontal|buffer
                    }
                },
            },
            opts = {
                log_level = "DEBUG",
            },
        },
    },
}

require("lazy.minit").repro({ spec = plugins })

-- Setup Tree-sitter
local ts_status, treesitter = pcall(require, "nvim-treesitter.configs")
if ts_status then
    treesitter.setup({
        ensure_installed = { "lua", "markdown", "markdown_inline", "yaml" },
        highlight = { enable = true },
    })
end

-- Setup completion
local cmp_status, cmp = pcall(require, "cmp")
if cmp_status then
    cmp.setup({
        mapping = cmp.mapping.preset.insert({
            ["<C-b>"] = cmp.mapping.scroll_docs(-4),
            ["<C-f>"] = cmp.mapping.scroll_docs(4),
            ["<C-Space>"] = cmp.mapping.complete(),
            ["<C-e>"] = cmp.mapping.abort(),
            ["<CR>"] = cmp.mapping.confirm({ select = true }),
            -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
        }),
    })
end
```

### Log output

```txt
```

### Describe the bug

The logic for `CodeCompanionChat Toggle` with `layout = "buffer"` could be improved.

### Reproduce the bug

1. Open two splits and run CodeCompanionChat
   ```bash
    nvim --clean -u minimal.lua \
      -c 'e foo' \
      -c 'split' \
      -c 'e bar' \
      -c 'CodeCompanionChat Toggle' \
      -c 'wincmd w'
    ```
2. `:CodeCompanionChat Toggle` and nothing happens.

### Fix

In this case `:CodeCompanionChat Toggle` should behave like `:CodeCompanionChat` and open a new codecompanion buffer linked to the current buffer.

### Improvement

With the `#buffer` variable there is a link created between a source code buffer and codecompanion buffer. When I have three buffers A, B, C with source files and corresponding codecompanion buffers cA1, cA2, cA3 and cB1.
The `#buffer` variable creates a map:

```
A <-> cA1, cA2, cA3
B <-> cB1
C <-> none
```

Now `:CodeCompanionChat Toggle` should behave like this:

1. When a buffer on the right side is focused -> Load the buffer on the left side in the window. (`^` Is the loaded buffer in the window)
     ```
     Before:
     A <-> cA1, cA2, ^cA3
     After:
     ^A <-> cA1, cA2, cA3
     ```
3. When a buffer on the left side is focused:
   1. A buffer on the right side exists -> Load the last opened buffer on the right side in the window.
      ```
      Before:
      ^A <-> cA1, cA2, cA3
      After:
      A <-> cA1, cA2, ^cA3
      ```
   2. When no buffer on right side exists -> Open a new codecompanion buffer
      ```
      Before:
      ^C <-> none
      After:
      C <-> ^cA1
      ```

And `:CodeCompanionChat` without the toggle should always load a new codecompanion buffer, when a source code buffer was focused.
When a codecompanion buffer is focused, the create a new codecompanion buffer which `#buffer` variables is the same as the original one.

### Keymaps

This could also be used for the `keymaps.next_chat`.

```
A <-> cA1, ^cA2, cA3
B <-> cB1
C <-> none
```

With `{`, `}` cycling through all codecompanion buffers: cA1, cA2, cA3, cB1 and 
`[` , `]` cycling only to the buffer A's codecompanion buffers: cA1, cA2, cA3

### Note

From the debug issue template:

```lua
vim.env.LAZY_STDPATH = ".repro"
```

Would not be `/tmp/foo` be nicer?

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` file from above and have shared this
- [X] I have shared the contents of the log file

**Comment by olimorris** [comment]
This is going to be challenging to debug and ultimately fix. Given this is only affecting a small number of users I'm going to prioritise adding new features but may come back to this in the future.
