### ISSUE TITLE
[Bug]: `#viewport` content is one line of

### ISSUE THREAD

**Issue by GordianDziwis** [olimorris/codecompanion.nvim#403]
### Your `minimal.lua` config

```

### Error messages

```

### Log output

```

### Health check output

```

### Describe the bug

[`vim.fn.line`](https://github.com/olimorris/codecompanion.nvim/blob/c79424deda06e63d3efb87167972d8c3f77d3e81/lua/codecompanion/utils/buffers.lua#L16) is 1-based while [`nvim_buf_get_lines`](https://github.com/olimorris/codecompanion.nvim/blob/c79424deda06e63d3efb87167972d8c3f77d3e81/lua/codecompanion/utils/buffers.lua#L79) is zero-based.

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` file from above and have shared this
- [X] I have shared the contents of the log file

**Comment by olimorris** [comment]
I can't reproduce this. It's working for me.
