### ISSUE TITLE
[Bug]: ollama adapter not working with new config

### ISSUE THREAD

**Issue by cleong14** [olimorris/codecompanion.nvim#42]
### Your `minimal.lua` config

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "olimorris/codecompanion.nvim",
    dependencies = {
      { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate"},
      "nvim-lua/plenary.nvim",
      {
        "stevearc/dressing.nvim", -- Optional: Improves the default Neovim UI
        opts = {},
      },
    },
    config = true
  }
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- setup treesitter
local ok, treesitter = pcall(require, "nvim-treesitter.configs")
if ok then
  treesitter.setup({
    ensure_installed = "all",
    ignore_install = { "phpdoc" }, -- list of parser which cause issues or crashes
    highlight = { enable = true },
  })
end
```

### Error messages

```lua
Error: Error malformed json: Expected value but found T_END at character 1
Error: Error malformed json: Expected value but found invalid token at character 1
```

### Health check output

```checkhealth
codecompanion: require("codecompanion.health").check()

codecompanion.nvim report
- Log file: /Users/chazleong/.config/nvim/.repro/state/nvim/codecompanion.log
- OK nvim-treesitter installed
- OK plenary.nvim installed
- OK dressing.nvim installed
- WARNING edgy.nvim not found
- OK curl installed
```

### Log output

`<EMPTY>`

### Expected Results

Ollama adapter throws no error and CodeCompanion works as usual.

### Actual Results

Ollama adapter throws error and CodeCompanion + Ollama is currently broken.

### Steps to Reproduce

1. Use latest version of `codecompanion.nvim`
2. Use `minimal.lua` config above
3. Run `nvim --clean -u minimal.lua`
4. Run `:CodeCompanionChat ollama`
5. Observe error

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue

**Comment by cleong14** [comment]
@olimorris Apologies, I tried to figure out the issue/fix on my own but I couldn't quite pinpoint what exactly was wrong with the Ollama adapter and I don't use the OpenAI or Anthropic adapters so I have no good point of reference as far as working/not working code.

**Comment by olimorris** [comment]
Hey @cleong14 you might need to reference https://github.com/olimorris/codecompanion.nvim/issues/9#issuecomment-2032458544.

I'd advise subscribing to that issue as I expect the APIs to change quite a lot.

**Comment by olimorris** [comment]
Just to check you have done `ollama serve` and have the `deepseek-coder:6.7b` model installed or are using a different model?

**Comment by cleong14** [comment]
Confirmed that I ran `ollama serve` beforehand/the instance is currently running and confirmed I that I hit the error when using `deepseek-coder:6.7b`. FWIW, I did try some of the other models I have and they all error too.

Ugh. I just retested everything and the `minimal.lua` works now, but my configs are breaking for some reason. I'm not sure where but I guess it's something I'm doing on my end.

One last question before closing this as it's not a bug, do the new configs affect the ollama adapter and the ability of adding additional default parameters?

For context, this is the error I get when I run `:CodeCompanionChat ollama` with my configs:

```lua
E5108: Error executing lua: vim/_editor.lua:0: nvim_exec2()..BufWriteCmd Autocommands for "<buffer=73>": Vim(append):Error executing lua callback: ...codecompanion.nvim/lua/codecompanion/strategies/chat.lua:539: attempt to call method 'set_params' (a nil value)
stack traceback:
	...codecompanion.nvim/lua/codecompanion/strategies/chat.lua:539: in function 'submit'
	...codecompanion.nvim/lua/codecompanion/strategies/chat.lua:201: in function <...codecompanion.nvim/lua/codecompanion/strategies/chat.lua:196>
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function 'cmd'
	...im/lazy/codecompanion.nvim/lua/codecompanion/keymaps.lua:9: in function 'rhs'
	...y/codecompanion.nvim/lua/codecompanion/utils/keymaps.lua:43: in function <...y/codecompanion.nvim/lua/codecompanion/utils/keymaps.lua:42>
stack traceback:
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function 'cmd'
	...im/lazy/codecompanion.nvim/lua/codecompanion/keymaps.lua:9: in function 'rhs'
	...y/codecompanion.nvim/lua/codecompanion/utils/keymaps.lua:43: in function <...y/codecompanion.nvim/lua/codecompanion/utils/keymaps.lua:42>
```

**Comment by olimorris** [comment]
My pleasure. Let me know if the additional default params aren't working as intended by opening up a new issue.

**Comment by olimorris** [comment]
You might have been on to something yesterday. I noticed that the OpenAI and Anthropic adapters weren't working well with custom overrides.

Let me know if you notice anything else.

**Comment by Gerodote** [comment]
@olimorris I got the same issue. 

I have next setup:
at plugins: ( neovim, lazy ... )
```
  {
    "olimorris/codecompanion.nvim",
    dependencies = {
      "nvim-treesitter/nvim-treesitter",
      "nvim-lua/plenary.nvim",
      {
        "stevearc/dressing.nvim", -- Optional: Improves the default Neovim UI
        opts = {},
      },
    },
    config = function()
      require "configs.codecompanion"
    end,
    lazy = false,
  },
```
at lua/configs/codecompanion.lua :
```
require("codecompanion").setup({
  strategies = {
    chat = "ollama",
    inline = "ollame",
  },
  log_level = "DEBUG"
})
```

in some terminals run `ollama serve` and `ollama run dolphin-mixtral:latest`

ok.. So, at the top of `:CodeCompanionChat` it says 
```
---
model: deepseek-coder:6.7b
temperature: 0.8
---
```
Which is not what I have. 
When it sends a prompt, it write the deepseek-coder and the prompt is not computes at ollama, because it's not the model running

at `~/.local/state/nvim/codecompanion.log` : 
```
[DEBUG] 2024-04-16 15:53:38
Stream Request: { "-sSL", "-D", "/run/user/1000/plenary_curl_60ea4b1d.headers", "--compressed", "-X", "POST", "--data-raw", '{"model":"deepseek-coder:6.7b","options":{"temperature":0.8},"messages":[{"content":"I want you to act as a senior JavaScript developer. I will give you specific code examples and ask you questions. I want you to advise me with explanations and code examples.","role":"system"},{"content":"\\n\\nI have the following code:\\n\\n```yaml\\nbuildType:\\n  default: debug\\n  choices:\\n    debug:\\n      short: Debug\\n      long: Emit debug information\\n      buildType: Debug\\n    release:\\n      short: Release\\n      long: Optimize generated code\\n      buildType: Release\\nmake json out of it","role":"user"}]}', "--no-buffer", "http://localhost:11434/api/chat" }
[DEBUG] 2024-04-16 15:53:52
Stream Request: { "-sSL", "-D", "/run/user/1000/plenary_curl_e2504396.headers", "--compressed", "-X", "POST", "--data-raw", '{"model":"deepseek-coder:6.7b","options":{"temperature":0.8},"messages":[{"content":"hey","role":"user"}]}', "--no-buffer", "http://localhost:11434/api/chat" }
```

**Comment by Gerodote** [comment]
I guess it has a relationship with https://github.com/olimorris/codecompanion.nvim/pull/45/commits/6f9a789f6abd21b8bf7bff473177547392dccc9a

**Comment by Gerodote** [comment]
ah, I got it sorry
