### ISSUE TITLE
[Bug]: Visual Selection + `:CodeCompanion <Prompt>` often replaces selection with a single line of concatenated text

### ISSUE THREAD

**Issue by GitMurf** [olimorris/codecompanion.nvim#426]
### Your `minimal.lua` config

N/A

### Error messages

N/A

### Log output

N/A

### Health check output

N/A

### Describe the bug

It seems that when not using a Prompt from the prompt library, and just doing a `:CodeCompanion <some question>` with a visual selection, the function for generating the selection as a code block is an outlier compared to all the other versions of similar functions in the code base. It is concatenating each line from the selection with a double space `"  "` as opposed to a `"\n"` line break.

What this leads to is a very inconsistent AI response where sometimes it acts smart enough to try and parse the lines itself without any line breaks and will return a mediocre result split by lines... but most of the time what I get back is a giant single string of the AI also responding with their lines as spaces and no line breaks (likely because it is trying to match what the user sent it).

Here is the code in question:

https://github.com/olimorris/codecompanion.nvim/blob/f0bc99111edad40fcca6628c4cefb38c93a42ab5/lua/codecompanion/strategies/inline.lua#L39-L46

As you notice, in several other places where similar line concatenations are done, it is using a `\n` which then the AI responses are always very good with the format coming back and actually having lines split properly in the diff view. Here for example is what a lot of the default prompt libraries use:

https://github.com/olimorris/codecompanion.nvim/blob/f0bc99111edad40fcca6628c4cefb38c93a42ab5/lua/codecompanion/helpers/actions.lua#L5-L21

You will notice in the last line it is using the same table.concat() of selection lines but properly uses `\n`.

### Reproduce the bug

Explained in detail above. Here is an example of the issue where 19 lines are coming back to the diff in one single line. To repro I simply:

1. Visually select some code
2. `:'<,'>CodeCompanion please update my selected code by removing code comments`
3. The diff shows the changes and it replaces the 19 lines with 1 giant concatenated line because it is replicating the format it received it in.

![image](https://github.com/user-attachments/assets/4f655f46-cc76-42bf-b9f8-843d6eb906a3)

And here is what it looked like when selecting it before code companion runs on it:

![image](https://github.com/user-attachments/assets/996b971b-b695-4032-953a-0cf0345423cd)

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` file from above and have shared this
- [X] I have shared the contents of the log file

**Comment by GitMurf** [comment]
> I'd very much welcome a PR on this! Thanks for raising.

Will do! May not be until tomorrow but hopefully tonight.

**Comment by e2r2fx** [comment]
This is a thing that can be solved by adding a system prompt instructing the LLM to keep its responses with the same formatting as the input. Whenever I do inline editing I do that by hand 😅 and it fixes any formatting errors of the response.

**Comment by GitMurf** [comment]
> This is a thing that can be solved by adding a system prompt instructing the LLM to keep its responses with the same formatting as the input. Whenever I do inline editing I do that by hand 😅 and it fixes any formatting errors of the response.

I did try this which definitely helped, but it was unpredictable and not consistent. Also that is part of the problem actually.... the "same format the input is in" is only what the AI model sees/receives over the API call. And that is the reason this is such a problem because this particular situation the plugin is preparing your selected text by combining into a single string (which is normal) BUT it is just using two spaces "  " to concatenate with for the line breaks as opposed to using "\n" line break. So the format the AI model sees is a giant string with no line breaks at all and has to guess where two spaces are in weird spots to try and guess where the line breaks actually are, but with code indentation etc. that makes it hard because there are plenty of consecutive spaces all over the place but that does not always mean it should be a line break.

Hopefully this makes sense @e2r2fx

**Comment by e2r2fx** [comment]
@GitMurf From my usage of 4o and sonnet 3.5 I haven't found any issues with the LLM properly formatting my code (there's always the option to hit a quick format after the suggestion comes in and that does it for me in some edge cases, but other than that no big deal.

**Comment by GitMurf** [comment]
> @GitMurf From my usage of 4o and sonnet 3.5 I haven't found any issues with the LLM properly formatting my code (there's always the option to hit a quick format after the suggestion comes in and that does it for me in some edge cases, but other than that no big deal.

One more thing to be clear, most all of the features in code companion do it "properly" and I agree with you completely. This is only in a certain circumstance when you are NOT using a prompt or an action etc and not using any slash commands or tools / agents etc. It is just when you select text and do `:CodeCompanion <do something>`. That is why it is kind of weird because everywhere else in the codebase, and all other regular features do it with a "\n" line break concat. I only experienced it cuz brand new to the plugin and didn't know how to do anything "fancy" yet with prompts etc haha

**Comment by GitMurf** [comment]
> ...there's always the option to hit a quick format after the suggestion comes in and that does it for me in some edge cases...

I heavily use the Diff feature and when formatting is off it throws the diff off making it look like everything has changed in some way. Anyways, glad you aren't having any issues!

**Comment by GitMurf** [comment]
PR #455 submitted to resolve this issue
