### ISSUE TITLE
[Bug]: Malformed JSON - Expected value but found T_END

### ISSUE THREAD

**Issue by ADGEfficiency** [olimorris/codecompanion.nvim#43]
### Your `minimal.lua` config

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--single-branch",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)

-- Your CodeCompanion setup
local plugins = {
	{
		"olimorris/codecompanion.nvim",
		dependencies = {
			{ "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
			"nvim-lua/plenary.nvim",
			"nvim-telescope/telescope.nvim",
			{
				"stevearc/dressing.nvim",
				opts = {},
			},
		},
		config = function()
			require("codecompanion").setup({
				strategies = { -- Change the adapters as required
					chat = "openai",
					inline = "openai",
				},
			})
		end,
	},
}

require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

-- setup treesitter
local ok, treesitter = pcall(require, "nvim-treesitter.configs")
if ok then
	treesitter.setup({
		ensure_installed = "all",
		ignore_install = { "phpdoc" }, -- list of parser which cause issues or crashes
		highlight = { enable = true },
	})
end
```

### Error messages

```lua
Error: Error malformed json: Expected value but found T_END at character 1                                                         
   
Error: Error malformed json: Expected value but found invalid token at character 1
Press ENTER or type command to continue
Error: Error malformed json: Expected the end but found T_COLON at character 12
Press ENTER or type command to continue
Error: Error malformed json: Expected the end but found T_COLON at character 9
Press ENTER or type command to continue
Error: Error malformed json: Expected the end but found T_COLON at character 10
Press ENTER or type command to continue
Error: Error malformed json: Expected the end but found T_COLON at character 9
Press ENTER or type command to continue
Error: Error malformed json: Expected value but found T_END at character 1
Press ENTER or type command to continue
Error: Error malformed json: Expected value but found T_END at character 1
```

### Health check output

```
codecompanion: require("codecompanion.health").check()

codecompanion.nvim report
- Log file: /Users/adam/.repro/state/nvim/codecompanion.log
- OK nvim-treesitter installed
- OK plenary.nvim installed
- OK dressing.nvim installed
- WARNING edgy.nvim not found
- OK curl installed
```

### Log output

Log file is empty.

### Expect to happen

When I use the `:CodeCompanionChat`, after typing a prompt and saving the buffer, to get back a prompt.

### What happens

I get the malformed JSON error when I save the buffer with a prompt.

### Plugin Version

When I look at the plugin code in ` ~/.repro/plugins/codecompanion.nvim`, I'm on this commit `1d081640d4854d619a5746532ffd6073b40bf35e`, made on Sat Apr 6 16:30:47.

I have checked that I have the env var for Open AI with:

```lua
:lua print(vim.fn.getenv("OPENAI_API_KEY"))                                                                                       
```

### Reproduce the bug

1. `:CodeCompanionChat`,
2. Type a prompt (I use `Hello`),
3. Then I get the `Malformed JSON` error.

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue

**Comment by olimorris** [comment]
I had this the other day and it was because my API credits had run out. Can you confirm this isn't the case for you?

**Comment by olimorris** [comment]
@ADGEfficiency any luck?

**Comment by olimorris** [comment]
I pushed a fix to the OpenAI adapter to better handle errors from the endpoint. You should see a more meaningful message rather than "malformed JSON" which told us nothing.

Frustratingly, OpenAI _stream_ errors which is a nuisance to have to handle (Anthropic are nice enough to just push the full error message in one).

**Comment by ADGEfficiency** [comment]
> @ADGEfficiency any luck?

Yes - the lack of credits was the issue.  You can close this now.

> I pushed a fix to the OpenAI adapter to better handle errors from the endpoint. You should see a more meaningful message rather than "malformed JSON" which told us nothing.

That's great - unfortunately now that I have credits I can't test it!

Next time I run out I'll be able to check out the fix - great idea.

Really love the plugin - great work!
