### ISSUE TITLE
[Bug]: without dressing / telescope :'<,'>CodeCompanionActions doesn't work

### ISSUE THREAD

**Issue by lucax88x** [olimorris/codecompanion.nvim#44]
### Your `minimal.lua` config

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--single-branch",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)

-- Your CodeCompanion setup
local plugins = {
	{
		"olimorris/codecompanion.nvim",
		dependencies = {
			{ "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
			"nvim-lua/plenary.nvim",
			-- "nvim-telescope/telescope.nvim",
			-- {
			--   "stevearc/dressing.nvim",
			--   opts = {},
			-- },
		},
		config = function()
			require("codecompanion").setup({
				strategies = { -- Change the adapters as required
					chat = "openai",
					inline = "openai",
				},
			})
		end,
	},
	{
		"ibhagwan/fzf-lua",
		branch = "main",
		init = function()
			--require("fzf-lua").register_ui_select()
		end,
	},
}

require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

-- setup treesitter
local ok, treesitter = pcall(require, "nvim-treesitter.configs")
if ok then
	treesitter.setup({
		ensure_installed = "all",
		ignore_install = { "phpdoc" }, -- list of parser which cause issues or crashes
		highlight = { enable = true },
	})
end
```

### Health check output

no need

### Log output

no logs

### Describe the bug

The problematic command is :CodeCompanionActions in visual mode or simply :'<,'>CodeCompanionActions.

So, if you don't use any ui lib (dressing) it works perfectly.

But if you use something else, such as the default nvim one, the fzf-lua one and the noice one, it will not work.

1) default and noice, same behavior

<img width="1296" alt="Screenshot 2024-04-11 at 21 13 08" src="https://github.com/olimorris/codecompanion.nvim/assets/6294464/3f6330a2-a7b1-4d67-9d71-1cc07c603dfa">

Cannot input any selection

2) fzf-lua popup opens for a second, then disappear before even selecting (uncomment fzf-lua ui-select to test)

### Reproduce the bug

1. open the nvim with minimal lua
2. run  :'<,'>CodeCompanionActions
3. cannot select any option, only close popup

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue

**Comment by olimorris** [comment]
As this sits outside of my use case the resolution for this would be to specify that dressing has to be installed.

Happy to accept a PR for this though.
