### ISSUE TITLE
[Bug]: Help tags slash command max lines is too small

### ISSUE THREAD

**Issue by GitMurf** [olimorris/codecompanion.nvim#515]
### Your `minimal.lua` config

N/A

### Error messages

N/A

### Log output

N/A

### Health check output

N/A

### Describe the bug

Help tags slash commands appear to cutoff at a total of 128 lines of content (there is a token cutoff too but I have not seen that come into play yet as an issue). With that, it really is half of that at 64 lines because it grabs the 64 lines above and 64 lines below the position of the help tag in the help file.

The idea of this is not bad at all! The problem is:

1. The limit is too small
2. We cannot configure / change it as users

The example is ironically with the CodeCompanion plugin ;) I added the help tag for `codecompanion-configuration` because I wanted to have CodeCompanion help me add a few custom keymaps and that part of the readme is under this tag. Well this part for the custom keymaps is actually around 130 lines away. So the "lines limit" would have to be more than doubled as it currently stands to allow for this scenario.

Here is the code that sets these limits: https://github.com/olimorris/codecompanion.nvim/blob/953b20dabf63e4e5c7b30b9d32cd1136291aceb1/lua/codecompanion/strategies/chat/slash_commands/help.lua#L10-L16

p.s. as an aside, the other contributing factor is that CodeCompanion probably could add more help tags so that you can focus your search closer to the tag since the `codecompanion-configuration` tag is quite large and there is nothing in between that and the custom keymaps example in the readme.

### Reproduce the bug

Explained in description...

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` file from above and have shared this
- [X] I have shared the contents of the log file

**Comment by olimorris** [comment]
Firstly, that is exactly how I hoped people would be using the plugin 😄. I'm hoping to combine the README with the `config.lua` file into an "LLM Friendly" vim doc to make this even more powerful.

Appreciate your comments regarding the line length too. `max_lines` are now customisable in your configuration and I've done away with any token count.
