### ISSUE TITLE
[Bug]: The Blink.cmp Completion isn't working.

### ISSUE THREAD

**Issue by MuntasirSZN** [olimorris/codecompanion.nvim#523]
### Your `minimal.lua` config
```lua
---@diagnostic disable: missing-fields

--NOTE: Set config path to enable the copilot adapter to work.
--It will search the follwoing paths for the for copilot token:
--  - "$CODECOMPANION_TOKEN_PATH/github-copilot/hosts.json"
--  - "$CODECOMPANION_TOKEN_PATH/github-copilot/apps.json"
vim.env["CODECOMPANION_TOKEN_PATH"] = vim.fn.expand("~/.config")

vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

-- Your CodeCompanion setup
local plugins = {
	{
		"olimorris/codecompanion.nvim",
		dependencies = {
			{ "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
			{ "nvim-lua/plenary.nvim" },
			{ "stevearc/dressing.nvim", opts = {} },
			{ "nvim-telescope/telescope.nvim" },
			{ "saghen/blink.cmp", version = "*" },
			{
				{ "L3MON4D3/LuaSnip", build = "make install_jsregexp" },
				"rafamadriz/friendly-snippets",
			},
		},
		opts = {
			strategies = {
				chat = {
					adapter = "openai_compatible",
				},
				inline = {
					adapter = "openai_compatible",
				},
				agent = {
					adapter = "openai_compatible",
				},
			},
			adapters = {
				openai_compatible = function()
					return require("codecompanion.adapters").extend("openai_compatible", {
						env = {
							url = "https://glhf.chat",
							api_key = "i_used_op, didnt work_so, direct paste",
							chat_url = "/api/openai/v1/chat/completions",
						},
						schema = {
							model = {
								-- Or any GLHF model!
								default = "hf:Qwen/Qwen2.5-72B-Instruct",
							},
							num_ctx = {
								default = 32768,
							},
						},
					})
				end,
			},
		},
	},
}

require("lazy.minit").repro({ spec = plugins })

-- Setup Tree-sitter
local ts_status, treesitter = pcall(require, "nvim-treesitter.configs")
if ts_status then
	treesitter.setup({
		ensure_installed = { "lua", "markdown", "markdown_inline", "yaml" },
		highlight = { enable = true },
	})
end

local blink_status, blink = pcall(require, "blink.cmp")

if blink_status then
	blink.setup({
		keymap = { preset = "default" },

		appearance = {
			-- Sets the fallback highlight groups to nvim-cmp's highlight groups
			-- Useful for when your theme doesn't support blink.cmp
			-- will be removed in a future release
			use_nvim_cmp_as_default = true,
			-- Set to 'mono' for 'Nerd Font Mono' or 'normal' for 'Nerd Font'
			-- Adjusts spacing to ensure icons are aligned
			nerd_font_variant = "mono",
		},

		-- default list of enabled providers defined so that you can extend it
		-- elsewhere in your config, without redefining it, via `opts_extend`
		sources = {
			completion = {
				enabled_providers = { "lsp", "path", "snippets", "buffer", "codecompanion" },
			},
			providers = {
				codecompanion = {
					name = "CodeCompanion",
					module = "codecompanion.providers.completion.blink",
					enabled = true,
				},
			},
		},

		-- experimental auto-brackets support
		-- completion = { accept = { auto_brackets = { enabled = true } } }

		-- experimental signature help support
		-- signature = { enabled = true }
	})
end

```
### Error messages

NONE

### Log output

NONE

### Health check output

```txt

==============================================================================
codecompanion: require("codecompanion.health").check()

- Neovim version: 0.10.2
- Log file: /home/muntasir/.local/state/nvim/codecompanion.log

Plugins: ~
- OK plenary.nvim installed
- OK nvim-treesitter installed

Tree-sitter parsers: ~
- OK markdown parser installed
- OK yaml parser installed

Libraries: ~
- OK curl installed


```

### Describe the bug

Blink should show the completion, but it doesn't. See my blink config:
```lua
	{
		"saghen/blink.cmp",
		lazy = false,
		version = "*",
		dependencies = {
			{ "L3MON4D3/LuaSnip", build = "make install_jsregexp" },
			"rafamadriz/friendly-snippets",
		},
		---@module 'blink.cmp'
		---@type blink.cmp.Config
		opts = {
			snippets = {
				expand = function(snippet)
					require("luasnip").lsp_expand(snippet)
				end,
				active = function(filter)
					if filter and filter.direction then
						return require("luasnip").jumpable(filter.direction)
					end
					return require("luasnip").in_snippet()
				end,
				jump = function(direction)
					require("luasnip").jump(direction)
				end,
			},
			sources = {
				completion = {
					enabled_providers = { "luasnip", "lsp", "path", "snippets", "buffer", "codecompanion" },
				},
				providers = {
					codecompanion = {
						name = "CodeCompanion",
						module = "codecompanion.providers.completion.blink",
						enabled = true,
					},
				},
			},
			keymap = { preset = "enter" },
			completion = {
				menu = {
					draw = {
						columns = { { "kind_icon", "label", gap = 1 }, { "kind" } },
					},
				},
			},
			vim.api.nvim_set_hl(0, "BlinkCmpMenu", { bg = "#212136", fg = "#cdd6f4" }),
			vim.api.nvim_set_hl(0, "BlinkCmpMenuBorder", { bg = "#1e1e2e", fg = "#585b70" }),
			vim.api.nvim_set_hl(0, "BlinkCmpDoc", { bg = "#212136", fg = "#cdd6f4" }),
			vim.api.nvim_set_hl(0, "BlinkCmpDocBorder", { bg = "#1e1e2e", fg = "#585b70" }),
			appearance = {
				use_nvim_cmp_as_default = true,
				nerd_font_variant = "normal",
				kind_icons = {
					Array = " ",
					Boolean = "󰨙 ",
					Class = " ",
					Codeium = "󰘦 ",
					Color = " ",
					Control = " ",
					Collapsed = " ",
					Constant = "  ",
					Constructor = " ",
					Copilot = " ",
					Enum = " ",
					EnumMember = " ",
					Event = " ",
					Field = "  ",
					File = " ",
					Folder = "  ",
					Function = "󰊕 ",
					Interface = " ",
					Key = " ",
					Keyword = " ",
					Method = " ",
					Module = " ",
					Namespace = "󰦮 ",
					Null = " ",
					Number = "󰎠 ",
					Object = " ",
					Operator = " ",
					Package = " ",
					Property = " ",
					Reference = " ",
					Snippet = " ",
					String = " ",
					Struct = "  ",
					TabNine = "󰏚 ",
					Text = " ",
					TypeParameter = " ",
					Unit = " ",
					Value = " ",
					Variable = " ",
				},
			},
		},
	},
```

But it doesnt show when i type like `/` or `#` like that.
![image](https://github.com/user-attachments/assets/d06b315a-ba92-4713-b58b-23f091e60979)
See also.
![image](https://github.com/user-attachments/assets/bf4ecfde-fd44-4e96-9b57-ca5b5ad915ed)

### Reproduce the bug

1. Inject my config.
2. Open A Chat Window.
3. See that completion doesn't work.

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` file from above and have shared this
- [X] I have shared the contents of the log file

**Comment by olimorris** [comment]
It's definitely [working](https://github.com/olimorris/codecompanion.nvim/discussions/381#discussioncomment-11513972). Try this minimal config out:

```lua
---@diagnostic disable: missing-fields

--NOTE: Set config path to enable the copilot adapter to work.
--It will search the follwoing paths for the for copilot token:
--  - "$CODECOMPANION_TOKEN_PATH/github-copilot/hosts.json"
--  - "$CODECOMPANION_TOKEN_PATH/github-copilot/apps.json"
vim.env["CODECOMPANION_TOKEN_PATH"] = vim.fn.expand("~/.config")

vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

-- Your CodeCompanion setup
local plugins = {
  {
    "olimorris/codecompanion.nvim",
    dependencies = {
      { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
      { "nvim-lua/plenary.nvim" },
      -- Comment this out if you don't want to setup blink.cmp
      {
        "saghen/blink.cmp",
        lazy = false,
        build = "cargo build --release",
        opts = {
          -- 'enter' for mappings similar to 'super-tab' but with 'enter' to accept
          keymap = {
            preset = "enter",
            ["<S-Tab>"] = { "select_prev", "fallback" },
            ["<Tab>"] = { "select_next", "fallback" },
          },
          sources = {
            completion = {
              enabled_providers = { "lsp", "path", "buffer", "codecompanion" },
            },
            providers = {
              codecompanion = {
                name = "CodeCompanion",
                module = "codecompanion.providers.completion.blink",
                enabled = true,
              },
            },
          },
        },
      },
    },
    opts = {
      --Refer to: https://github.com/olimorris/codecompanion.nvim/blob/main/lua/codecompanion/config.lua
      strategies = {
        --NOTE: Change the adapter as required
        chat = { adapter = "copilot" },
        inline = { adapter = "copilot" },
      },
      opts = {
        log_level = "DEBUG",
      },
    },
  },
}

require("lazy.minit").repro({ spec = plugins })

-- Setup Tree-sitter
local ts_status, treesitter = pcall(require, "nvim-treesitter.configs")
if ts_status then
  treesitter.setup({
    ensure_installed = { "lua", "markdown", "markdown_inline", "yaml" },
    highlight = { enable = true },
  })
end
```

If you identify a bug, open the issue again and share the minimal.lua.

**Comment by olimorris** [comment]
FYI, blink hasn't created a release with the fix which enables codecompanion to work. I think `version = "*"` is the issue.

**Comment by MuntasirSZN** [comment]
> FYI, blink hasn't created a release with the fix which enables codecompanion to work. I think `version = "*"` is 

Maybe.

**Comment by MuntasirSZN** [comment]
> It's definitely [working](https://github.com/olimorris/codecompanion.nvim/discussions/381#discussioncomment-11513972). Try this minimal config out:
> 
> ```lua
> ---@diagnostic disable: missing-fields
> 
> --NOTE: Set config path to enable the copilot adapter to work.
> --It will search the follwoing paths for the for copilot token:
> --  - "$CODECOMPANION_TOKEN_PATH/github-copilot/hosts.json"
> --  - "$CODECOMPANION_TOKEN_PATH/github-copilot/apps.json"
> vim.env["CODECOMPANION_TOKEN_PATH"] = vim.fn.expand("~/.config")
> 
> vim.env.LAZY_STDPATH = ".repro"
> load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()
> 
> -- Your CodeCompanion setup
> local plugins = {
>   {
>     "olimorris/codecompanion.nvim",
>     dependencies = {
>       { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
>       { "nvim-lua/plenary.nvim" },
>       -- Comment this out if you don't want to setup blink.cmp
>       {
>         "saghen/blink.cmp",
>         lazy = false,
>         build = "cargo build --release",
>         opts = {
>           -- 'enter' for mappings similar to 'super-tab' but with 'enter' to accept
>           keymap = {
>             preset = "enter",
>             ["<S-Tab>"] = { "select_prev", "fallback" },
>             ["<Tab>"] = { "select_next", "fallback" },
>           },
>           sources = {
>             completion = {
>               enabled_providers = { "lsp", "path", "buffer", "codecompanion" },
>             },
>             providers = {
>               codecompanion = {
>                 name = "CodeCompanion",
>                 module = "codecompanion.providers.completion.blink",
>                 enabled = true,
>               },
>             },
>           },
>         },
>       },
>     },
>     opts = {
>       --Refer to: https://github.com/olimorris/codecompanion.nvim/blob/main/lua/codecompanion/config.lua
>       strategies = {
>         --NOTE: Change the adapter as required
>         chat = { adapter = "copilot" },
>         inline = { adapter = "copilot" },
>       },
>       opts = {
>         log_level = "DEBUG",
>       },
>     },
>   },
> }
> 
> require("lazy.minit").repro({ spec = plugins })
> 
> -- Setup Tree-sitter
> local ts_status, treesitter = pcall(require, "nvim-treesitter.configs")
> if ts_status then
>   treesitter.setup({
>     ensure_installed = { "lua", "markdown", "markdown_inline", "yaml" },
>     highlight = { enable = true },
>   })
> end
> ```
> 
> If you identify a bug, open the issue again and share the minimal.lua.

![image](https://github.com/user-attachments/assets/9a7ac80f-92c6-4465-9241-734ca1337964)
No sir.

**Comment by MuntasirSZN** [comment]
![image](https://github.com/user-attachments/assets/f7e6ffb1-f7de-4868-8487-648bacfe69fa)

**Comment by MuntasirSZN** [comment]
Ok Finally Found It. Remove the `version = "*"` and replace with `build = "cargo build --release"`.  Thats the solve. Though, the completion window opens, there isn't any options popping up.
![image](https://github.com/user-attachments/assets/25e8390f-5346-412d-857f-176d910a907c)
This fetch is actually a vim function, not a completion.

**Comment by olimorris** [comment]
Glad to see it's working 👍

**Comment by MuntasirSZN** [comment]
> Glad to see it's working 👍

@olimorris As Its A Problem, And As Blink.cmp's repo says to use version tag, I think this should be said.

**Comment by olimorris** [comment]
There are regular releases to blink so I'm sure this will get packaged up in one today or tomorrow.

**Comment by MuntasirSZN** [comment]
> There are regular releases to blink so I'm sure this will get packaged up in one today or tomorrow.

Ok, waiting for that. In the meantime, following your method.
