### ISSUE TITLE
[Bug]: Attempt to call method 'set_params' (a nil value) when using inline

### ISSUE THREAD

**Issue by sQVe** [olimorris/codecompanion.nvim#54]
### Your `minimal.lua` config

The default minimal config provided above.

### Error messages

```lua                                                      
Error executing vim.schedule lua callback: ...decompanion.nvim/lua/codecompanion/strategies/inl
ine.lua:205: attempt to call method 'set_params' (a nil value)                                 
stack traceback:                                                                               
        ...decompanion.nvim/lua/codecompanion/strategies/inline.lua:205: in function 'get_inlin
e_output'                                                                                      
        ...decompanion.nvim/lua/codecompanion/strategies/inline.lua:338: in function 'cb'      
        .../sqve/.repro/plugins/dressing.nvim/lua/dressing/util.lua:206: in function <.../sqve/
.repro/plugins/dressing.nvim/lua/dressing/util.lua:202>
```

### Health check output

```
codecompanion.nvim report ~
- Log file: /home/sqve/.repro/state/nvim/codecompanion.log
- OK plenary.nvim installed
- OK nvim-treesitter installed
- OK telescope.nvim installed
- OK dressing.nvim installed
- WARNING edgy.nvim not found
- OK curl installed
- OK base64 installed
```

### Log output

File is empty

### What I expected to happen

The plugin should generate a unit test for me

### What actually happened

An error was produced.

### Reproduce the bug

1. Use default minimal config.
2. Create new file.
3. Write `test`.
4. Select `test` and run `CodeCompanion`.
5. Write `Translate this to a random language` in the **prompt**.

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue

**Comment by olimorris** [comment]
Thanks so much for raising this! This was caused my by attempt to streamline how the plugin works with adapters in b25762cd7002f2f77029fc9934213183093feb3b. Let me know if this solves it and how you get on with the plugin!
