### ISSUE TITLE
[Bug]: code companion does not work with nvim-treesitter @ main

### ISSUE THREAD

**Issue by dsully** [olimorris/codecompanion.nvim#542]
### Your `minimal.lua` config

```lua
{
        "nvim-treesitter/nvim-treesitter",
        branch = "main",
        ...
}
```

### Error messages

```lua
E5108: Error executing lua: ...odecompanion.nvim/lua/codecompanion/utils/treesitter.lua:2: module 'nvim-treesitter.ts_utils' not found:
	no field package.preload['nvim-treesitter.ts_utils']
	cache_loader: module 'nvim-treesitter.ts_utils' not found
	cache_loader_lib: module 'nvim-treesitter.ts_utils' not found
	no file './nvim-treesitter/ts_utils.lua'
```

### Log output

N/A

### Describe the bug

`nvim-treesitter` on the main branch removes both `ts_utils` and `parsers.lua` returns just a table.

It'd be great if `codecompanion` could be updated to support both the `master` and `main` branches.

`goto_node` and the functions it calls are pretty simple if pulling those in is the correct approach.

The parser call should be replaced with something like:

```lua
local root_parser = vim.treesitter.get_parser(buffer)
root_parser:parse(true)
```

Happy to put together a PR if you prefer. Thanks!

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` file from above and have shared this
- [X] I have shared the contents of the log file

**Comment by olimorris** [comment]
Thanks for raising this. I actually hadn't realised that `main` was where the rewrite was taking place so this is great to have sight of.

And I would love a PR to fix this. If it makes sense to extract a lot of Tree-sitter logic to a utility file, please go for it.

**Comment by robclancy** [comment]
Can the nvim-treesitter dep not be removed?
