### ISSUE TITLE
[Bug]: Inline edit is broken for Anthropic Adapter

### ISSUE THREAD

**Issue by meridionaljet** [olimorris/codecompanion.nvim#55]
### Your `minimal.lua` config

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--single-branch",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)

-- Your CodeCompanion setup
local plugins = {
	{
		"olimorris/codecompanion.nvim",
		dependencies = {
			{ "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
			"nvim-lua/plenary.nvim",
			"nvim-telescope/telescope.nvim",
			{
				"stevearc/dressing.nvim",
				opts = {},
			},
		},
		config = function()
			local adapters = require("codecompanion.adapters")
			require("codecompanion").setup({
				adapters = {
					anthropic = adapters.use("anthropic", {
						schema = {
							model = {
								default = "claude-3-5-sonnet-20240620",
							},
						},
					}),
				},
				strategies = {
					chat = "anthropic",
					inline = "anthropic",
					tools = "anthropic",
				},
				log_level = "TRACE",
			})
		end,
	},
}

require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

-- setup treesitter
local ok, treesitter = pcall(require, "nvim-treesitter.configs")
if ok then
	treesitter.setup({
		ensure_installed = "all",
		ignore_install = { "phpdoc" }, -- list of parser which cause issues or crashes
		highlight = { enable = true },
	})
end
```

### Health check output

codecompanion: require("codecompanion.health").check()

codecompanion.nvim report
- Log file: /home/user/.repro/state/nvim/codecompanion.log
- OK plenary.nvim installed
- OK nvim-treesitter installed
- OK telescope.nvim installed
- OK dressing.nvim installed
- OK curl installed
- OK base64 installed

### Log output

The log is empty.

### Describe the bug

When using the Anthropic adapter as in the modified minimal config, visually selecting a code block and typing `:CodeCompanion`, followed by a prompt, results in no LLM response being inserted into the buffer. Instead, a string like "replace|true" gets inserted at the location of the selection. This string appears to be the value of the `placement` variable in `inline.lua`: https://github.com/olimorris/codecompanion.nvim/blob/41f64e2589b490758d6db2418e67da8e704eda2b/lua/codecompanion/strategies/inline.lua#L186

When using the OpenAI adapter, this does not happen, and the LLM response is inserted into the buffer as expected.

### Reproduce the bug

1. Visually select lines of code
2. Type `:CodeCompanion`
3. Write a prompt

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue
- [X] I have shared the contents of the log file

**Comment by olimorris** [comment]
Thanks for this! Coincidentally I found this at the same time as have been enjoying `claude-3-5-sonnet` 😄 .

This should now be fixed as per https://github.com/olimorris/codecompanion.nvim/commit/4eb71e61b6b95bdc777e6191b0c598ba9d2f3135.
