### ISSUE TITLE
[Bug]: `display.chat.window.width = 0` behavior changes

### ISSUE THREAD

**Issue by Bekaboo** [olimorris/codecompanion.nvim#570]
### Your `minimal.lua` config

```lua
---@diagnostic disable: missing-fields

--[[
NOTE: Set the config path to enable the copilot adapter to work.
It will search the following paths for a token:
  - "$CODECOMPANION_TOKEN_PATH/github-copilot/hosts.json"
  - "$CODECOMPANION_TOKEN_PATH/github-copilot/apps.json"
--]]
vim.env['CODECOMPANION_TOKEN_PATH'] = vim.fn.expand('~/.config')

vim.env.LAZY_STDPATH = '.repro'
load(
  vim.fn.system(
    'curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua'
  )
)()

-- Your CodeCompanion setup
local plugins = {
  {
    'olimorris/codecompanion.nvim',
    dependencies = {
      {
        'nvim-treesitter/nvim-treesitter',
        build = ':TSUpdate',
      },
      { 'nvim-lua/plenary.nvim' },
    },
    opts = {
      --Refer to: https://github.com/olimorris/codecompanion.nvim/blob/main/lua/codecompanion/config.lua
      strategies = {
        --NOTE: Change the adapter as required
        chat = { adapter = 'anthropic' },
        inline = { adapter = 'anthropic' },
      },
      opts = {
        log_level = 'DEBUG',
      },
      display = {
        chat = {
          window = {
            width = 0,
          },
        },
      },
    },
  },
}

require('lazy.minit').repro({ spec = plugins })

-- Setup Tree-sitter
local ts_status, treesitter = pcall(require, 'nvim-treesitter.configs')
if ts_status then
  treesitter.setup({
    ensure_installed = {
      'lua',
      'markdown',
      'markdown_inline',
      'yaml',
    },
    highlight = { enable = true },
  })
end

-- Setup nvim-cmp
-- local cmp_status, cmp = pcall(require, "cmp")
-- if cmp_status then
--   cmp.setup({
--     mapping = cmp.mapping.preset.insert({
--       ["<C-b>"] = cmp.mapping.scroll_docs(-4),
--       ["<C-f>"] = cmp.mapping.scroll_docs(4),
--       ["<C-Space>"] = cmp.mapping.complete(),
--       ["<C-e>"] = cmp.mapping.abort(),
--       ["<CR>"] = cmp.mapping.confirm({ select = true }),
--       -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
--     }),
--   })
-- end
```

### Error messages

N/A

### Log output

Log file not created.

### Health check output

```
codecompanion: require("codecompanion.health").check()

- Neovim version: 0.10.3
- Log file: /home/zeng/scratches/.repro//state/nvim.test/codecompanion.log

Plugins: ~
- OK plenary.nvim installed
- OK nvim-treesitter installed

Tree-sitter parsers: ~
- OK markdown parser installed
- OK yaml parser installed

Libraries: ~
- OK curl installed
```

### Describe the bug

Previously if `width` is set to 0, codecompanion will do a normal vertical split (`:vsplit`), this is especially convenient compared to the default behavior (vertically split then resize to 0.45 of the screen) if you already have two windows in vertical split before opening codecompanion:

Before opening codecompanion buffer:

![image](https://github.com/user-attachments/assets/519bd3bd-d5e6-4e4c-992f-3ad40ec28edf)

With `width = 0` after opening codecompanion buffer (in older version):

![image](https://github.com/user-attachments/assets/dd623daf-f031-4cf8-b002-cb047d86f304)

Without `width = 0` after opening codecompanion buffer (observe how the right split being "squeezed" by codecompanion):

![image](https://github.com/user-attachments/assets/c2b3f3c5-b33f-43d1-98f4-ce7362578512)

With `width = 0` after opening codecompanion buffer (in latest version), the width of the chat buffer is set to 1:

![image](https://github.com/user-attachments/assets/0d8b16d8-356f-4ef1-ac65-8ca53f3f4787)

### Reproduce the bug

1. `nvim --clean -u minimal.lua`
2. `:vsplit | wincmd b | CodeCompanionChat`
3. The window width behavior is different from older versions

The bug is introduced by commit 7374192

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` file from above and have shared this
- [X] I have shared the contents of the log file

**Comment by olimorris** [comment]
Thanks for raising this. Unfortunately I never intended a width of zero to work in the first place and had never intended anyone would set that in their config.

**Comment by Bekaboo** [comment]
It will be nice if we can allow `width = false` to disable the resize behavior.
