### ISSUE TITLE
[Bug]: Ollama returns 404 to CodeCompanion

### ISSUE THREAD

**Issue by Mohamed-E-Fayed** [olimorris/codecompanion.nvim#83]
### Your `minimal.lua` config

-- the edits only:
require("codecompanion").setup()
require("codecompanion").setup({
 strategies = {
   chat = {
     adapter = "ollama",
   },
   inline = {
     adapter = "ollama",
   },
   agent = {
     adapter = "ollama",
   },
 },
opts = {
    log_level = "TRACE"
}
})

### Error messages

For using CodeCompanion in neovim, I receive no error messages.
However, when I check ollama logs, I get:
[GIN] 2024/08/02 - 18:38:38 | 200 |      61.041µs |       127.0.0.1 | HEAD     "/"
[GIN] 2024/08/02 - 18:38:38 | 200 |    3.076375ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/08/02 - 18:38:38 | 404 |     218.792µs |       127.0.0.1 | POST     "/api/chat"

### Health check output

==============================================================================
CodeCompanion: require("CodeCompanion.health").check()

codecompanion.nvim report ~
- Log file: /Users/mohamedfayed/.local/state/nvim/codecompanion.log
- OK plenary.nvim installed
- OK nvim-treesitter installed
- OK telescope.nvim installed
- OK dressing.nvim installed
- OK curl installed

### Log output

codecompanion.log
[codecompanion.log](https://github.com/user-attachments/files/16478616/codecompanion.log)

## Expected:

Some output in some form

## What Actually Happened

No output in neovim, and ollama logs showing that it returned 404 for the request by CodeCompanion.
when I use bash and curl, like below, it works.

$ curl -X POST http://127.0.0.1:11434/api/chat -H "Content-Type: application/json" -d '{"api_key": "your-api-key", "model": "custom_llama_3.1", "input": "Hello, World!"}'
The ollama server logs:

[GIN] 2024/08/02 - 12:11:57 | 200 |   1.56818975s |       127.0.0.1 | POST     "/api/chat"
## Environment:

Mac OS 13.6 Apple Silicon
ollama version is 0.3.0
NVIM v0.10.0

Thank you so much 

### Reproduce the bug

I was trying adapting your installation to my current setup, but I get 404 when CodeCompanion send request to local Ollama setup.

Steps:

bash brew install ollama # it is working properly.
Copy your config.lua to ~/.config/nvim/lua/codecompanion_config.lua
add the following lines to my ~/.config/nvim/init.vim:
" For installation 
call plug#begin()
 Plug 'nvim-lua/plenary.nvim'
 Plug 'nvim-treesitter/nvim-treesitter'

 Plug 'olimorris/codecompanion.nvim'
call plug#end()

--for configurations, I added the same lines as above:
require("codecompanion").setup()
require("codecompanion").setup({
 strategies = {
   chat = {
     adapter = "ollama",
   },
   inline = {
     adapter = "ollama",
   },
   agent = {
     adapter = "ollama",
   },
 },
opts = {
    log_level = "TRACE"
}
})

4. run from bash bash nvim +PlugInstall , and it shows successful installation.
5. in a new file, do :CodeCompanion hello

Note: regarding testing with minimal.lua, neovim was hanging with me, so I was not able to do it.
I submitted this bug report even though based on our discussion [here](https://github.com/olimorris/codecompanion.nvim/discussions/79).

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue
- [X] I have shared the contents of the log file

**Comment by olimorris** [comment]
Sorry to be a nuisance but you need to follow the minimal.lua in the bug report. There's no way I can recreate your issue without it. Also, the issue is likely something with your configuration and this will help you identify it

**Comment by olimorris** [comment]
@Mohamed-E-Fayed - I've updated the bug report template so can you re-raise this as a new issue and follow the `minimal.lua` file? I can't recreate your issue without it.

**Comment by olimorris** [comment]
Btw, are you sure you have the default models the adapter uses, installed?

**Comment by Mohamed-E-Fayed** [comment]
Ok, I will recheck the minimal.lua. As I mentioned in the note, neovim was hanging with me and not responding after running $nvim --clean -u minimal.lua.

Regarding ensuring that the model exist, yes. You may check the curl request. I already use that model with $ollama run custom_llama_3.1. It is a local model, which is the default llama 3.1, but I added it manually.

Thank you so much

**Comment by Mohamed-E-Fayed** [comment]
I have just made another issue after succeeding in reusing your minima.lua 👍 https://github.com/olimorris/codecompanion.nvim/issues/86

Thank you so much
