### ISSUE TITLE
[Bug]: Ollama returns 404 to CodeCompanion

### ISSUE THREAD

**Issue by Mohamed-E-Fayed** [olimorris/codecompanion.nvim#86]
### Your `minimal.lua` config

local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- Your CodeCompanion setup
local plugins = {
  {
    "olimorris/codecompanion.nvim",
    dependencies = {
      { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate"},
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim",
      {
        "stevearc/dressing.nvim",
        opts = {},
      },
    },
    config = function()
      -- Refer to: https://github.com/olimorris/codecompanion.nvim/blob/main/lua/codecompanion/config.lua
      require("codecompanion").setup({
        strategies = { -- Change the adapters as required
          chat = { adapter = "ollama" },
          inline = { adapter = "ollama" },
          agent = { adapter = "ollama" },
        },
        log_level = "TRACE",
      })
    end,
  }
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- setup treesitter
local ok, treesitter = pcall(require, "nvim-treesitter.configs")
if ok then
  treesitter.setup({
    ensure_installed = "all",
    ignore_install = { "phpdoc" }, -- list of parser which cause issues or crashes
    highlight = { enable = true },
  })
end

### Error messages

I receive no error messages in neovim, but this is the total output for ollama logs after starting the server.

```
$ ollama serve 
2024/08/03 18:11:31 routes.go:1099: INFO server config env="map[OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/Users/mohamedfayed/.ollama/models OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://*] OLLAMA_RUNNERS_DIR: OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR:]"
time=2024-08-03T18:11:31.597+03:00 level=INFO source=images.go:784 msg="total blobs: 9"
time=2024-08-03T18:11:31.598+03:00 level=INFO source=images.go:791 msg="total unused blobs removed: 0"
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] POST   /api/pull                 --> github.com/ollama/ollama/server.(*Server).PullModelHandler-fm (5 handlers)
[GIN-debug] POST   /api/generate             --> github.com/ollama/ollama/server.(*Server).GenerateHandler-fm (5 handlers)
[GIN-debug] POST   /api/chat                 --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (5 handlers)
[GIN-debug] POST   /api/embed                --> github.com/ollama/ollama/server.(*Server).EmbedHandler-fm (5 handlers)
[GIN-debug] POST   /api/embeddings           --> github.com/ollama/ollama/server.(*Server).EmbeddingsHandler-fm (5 handlers)
[GIN-debug] POST   /api/create               --> github.com/ollama/ollama/server.(*Server).CreateModelHandler-fm (5 handlers)
[GIN-debug] POST   /api/push                 --> github.com/ollama/ollama/server.(*Server).PushModelHandler-fm (5 handlers)
[GIN-debug] POST   /api/copy                 --> github.com/ollama/ollama/server.(*Server).CopyModelHandler-fm (5 handlers)
[GIN-debug] DELETE /api/delete               --> github.com/ollama/ollama/server.(*Server).DeleteModelHandler-fm (5 handlers)
[GIN-debug] POST   /api/show                 --> github.com/ollama/ollama/server.(*Server).ShowModelHandler-fm (5 handlers)
[GIN-debug] POST   /api/blobs/:digest        --> github.com/ollama/ollama/server.(*Server).CreateBlobHandler-fm (5 handlers)
[GIN-debug] HEAD   /api/blobs/:digest        --> github.com/ollama/ollama/server.(*Server).HeadBlobHandler-fm (5 handlers)
[GIN-debug] GET    /api/ps                   --> github.com/ollama/ollama/server.(*Server).ProcessHandler-fm (5 handlers)
[GIN-debug] POST   /v1/chat/completions      --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (6 handlers)
[GIN-debug] POST   /v1/completions           --> github.com/ollama/ollama/server.(*Server).GenerateHandler-fm (6 handlers)
[GIN-debug] POST   /v1/embeddings            --> github.com/ollama/ollama/server.(*Server).EmbedHandler-fm (6 handlers)
[GIN-debug] GET    /v1/models                --> github.com/ollama/ollama/server.(*Server).ListModelsHandler-fm (6 handlers)
[GIN-debug] GET    /v1/models/:model         --> github.com/ollama/ollama/server.(*Server).ShowModelHandler-fm (6 handlers)
[GIN-debug] GET    /                         --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func1 (5 handlers)
[GIN-debug] GET    /api/tags                 --> github.com/ollama/ollama/server.(*Server).ListModelsHandler-fm (5 handlers)
[GIN-debug] GET    /api/version              --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func2 (5 handlers)
[GIN-debug] HEAD   /                         --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func1 (5 handlers)
[GIN-debug] HEAD   /api/tags                 --> github.com/ollama/ollama/server.(*Server).ListModelsHandler-fm (5 handlers)
[GIN-debug] HEAD   /api/version              --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func2 (5 handlers)
time=2024-08-03T18:11:31.598+03:00 level=INFO source=routes.go:1146 msg="Listening on 127.0.0.1:11434 (version 0.3.0)"
time=2024-08-03T18:11:31.602+03:00 level=INFO source=payload.go:30 msg="extracting embedded files" dir=/var/folders/dp/zrszmqsd4bv077jy_rj1szd00000gn/T/ollama3354584792/runners
time=2024-08-03T18:11:31.631+03:00 level=INFO source=payload.go:44 msg="Dynamic LLM libraries [metal]"
time=2024-08-03T18:11:31.659+03:00 level=INFO source=types.go:105 msg="inference compute" id=0 library=metal compute="" driver=0.0 name="" total="48.0 GiB" available="48.0 GiB"
[GIN] 2024/08/03 - 18:11:43 | 404 |    1.476625ms |       127.0.0.1 | POST     "/api/chat"



### Health check output


==============================================================================
codecompanion: require("codecompanion.health").check()

codecompanion.nvim report ~
- Log file: /Users/mohamedfayed/.config/nvim/.repro/state/nvim/codecompanion.log
- OK plenary.nvim installed
- OK nvim-treesitter installed
- OK telescope.nvim installed
- OK dressing.nvim installed
- OK curl installed


### Log output

[codecompanion.log](https://github.com/user-attachments/files/16481099/codecompanion.log)


### Describe the bug

# Expected

I expected to receive 200 for instance.
I was trying using curl, and it succeed:

```bash
$ curl -X POST http://127.0.0.1:11434/api/chat -H "Content-Type: application/json" -d '{"api_key": "your-api-key", "model": "custom_llama_3.1", "input": "Hello, World!"}'
{"model":"custom_llama_3.1","created_at":"2024-08-03T15:17:16.249323Z","message":{"role":"assistant","content":""},"done_reason":"load","done":true}
```

And logs of ollama are showing 👍 [GIN] 2024/08/03 - 18:40:25 | 404 |     437.041µs |       127.0.0.1 | POST     "/api/chat"

And of course was expecting something to show off in neovim.

# What happened

Nothing shows off in Neovim after running the. command.

I also found ollama logs are showing 404 instead of 200.

```
```
$ ollama serve 
2024/08/03 18:11:31 routes.go:1099: INFO server config env="map[OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/Users/mohamedfayed/.ollama/models OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://*] OLLAMA_RUNNERS_DIR: OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR:]"
time=2024-08-03T18:11:31.597+03:00 level=INFO source=images.go:784 msg="total blobs: 9"
time=2024-08-03T18:11:31.598+03:00 level=INFO source=images.go:791 msg="total unused blobs removed: 0"
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] POST   /api/pull                 --> github.com/ollama/ollama/server.(*Server).PullModelHandler-fm (5 handlers)
[GIN-debug] POST   /api/generate             --> github.com/ollama/ollama/server.(*Server).GenerateHandler-fm (5 handlers)
[GIN-debug] POST   /api/chat                 --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (5 handlers)
[GIN-debug] POST   /api/embed                --> github.com/ollama/ollama/server.(*Server).EmbedHandler-fm (5 handlers)
[GIN-debug] POST   /api/embeddings           --> github.com/ollama/ollama/server.(*Server).EmbeddingsHandler-fm (5 handlers)
[GIN-debug] POST   /api/create               --> github.com/ollama/ollama/server.(*Server).CreateModelHandler-fm (5 handlers)
[GIN-debug] POST   /api/push                 --> github.com/ollama/ollama/server.(*Server).PushModelHandler-fm (5 handlers)
[GIN-debug] POST   /api/copy                 --> github.com/ollama/ollama/server.(*Server).CopyModelHandler-fm (5 handlers)
[GIN-debug] DELETE /api/delete               --> github.com/ollama/ollama/server.(*Server).DeleteModelHandler-fm (5 handlers)
[GIN-debug] POST   /api/show                 --> github.com/ollama/ollama/server.(*Server).ShowModelHandler-fm (5 handlers)
[GIN-debug] POST   /api/blobs/:digest        --> github.com/ollama/ollama/server.(*Server).CreateBlobHandler-fm (5 handlers)
[GIN-debug] HEAD   /api/blobs/:digest        --> github.com/ollama/ollama/server.(*Server).HeadBlobHandler-fm (5 handlers)
[GIN-debug] GET    /api/ps                   --> github.com/ollama/ollama/server.(*Server).ProcessHandler-fm (5 handlers)
[GIN-debug] POST   /v1/chat/completions      --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (6 handlers)
[GIN-debug] POST   /v1/completions           --> github.com/ollama/ollama/server.(*Server).GenerateHandler-fm (6 handlers)
[GIN-debug] POST   /v1/embeddings            --> github.com/ollama/ollama/server.(*Server).EmbedHandler-fm (6 handlers)
[GIN-debug] GET    /v1/models                --> github.com/ollama/ollama/server.(*Server).ListModelsHandler-fm (6 handlers)
[GIN-debug] GET    /v1/models/:model         --> github.com/ollama/ollama/server.(*Server).ShowModelHandler-fm (6 handlers)
[GIN-debug] GET    /                         --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func1 (5 handlers)
[GIN-debug] GET    /api/tags                 --> github.com/ollama/ollama/server.(*Server).ListModelsHandler-fm (5 handlers)
[GIN-debug] GET    /api/version              --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func2 (5 handlers)
[GIN-debug] HEAD   /                         --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func1 (5 handlers)
[GIN-debug] HEAD   /api/tags                 --> github.com/ollama/ollama/server.(*Server).ListModelsHandler-fm (5 handlers)
[GIN-debug] HEAD   /api/version              --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func2 (5 handlers)
time=2024-08-03T18:11:31.598+03:00 level=INFO source=routes.go:1146 msg="Listening on 127.0.0.1:11434 (version 0.3.0)"
time=2024-08-03T18:11:31.602+03:00 level=INFO source=payload.go:30 msg="extracting embedded files" dir=/var/folders/dp/zrszmqsd4bv077jy_rj1szd00000gn/T/ollama3354584792/runners
time=2024-08-03T18:11:31.631+03:00 level=INFO source=payload.go:44 msg="Dynamic LLM libraries [metal]"
time=2024-08-03T18:11:31.659+03:00 level=INFO source=types.go:105 msg="inference compute" id=0 library=metal compute="" driver=0.0 name="" total="48.0 GiB" available="48.0 GiB"
[GIN] 2024/08/03 - 18:11:43 | 404 |    1.476625ms |       127.0.0.1 | POST     "/api/chat"
```

### Reproduce the bug

Note: I have also used the minimal.lua above and still get same results. You may check second steps list below.

## Steps:

1. bash brew install ollama # it is working properly.
2. Copy your config.lua to ~/.config/nvim/lua/codecompanion_config.lua
3. add the following lines to my ~/.config/nvim/init.vim:
" For installation
call plug#begin()
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-treesitter/nvim-treesitter'

Plug 'olimorris/codecompanion.nvim'
call plug#end()

--for configurations, I added the same lines as above:
require("codecompanion").setup()
require("codecompanion").setup({
strategies = {
chat = {
adapter = "ollama",
},
inline = {
adapter = "ollama",
},
agent = {
adapter = "ollama",
},
},
opts = {
log_level = "TRACE"
}
})

4. run from bash bash nvim +PlugInstall , and it shows successful installation.
5. in a new file, do :CodeCompanion hello

Steps using minimal.lua:
1. copy your minimal.lua, but replace "openai" with "ollama".
2. paste it to ~/.config/nvim/init.lua and ~/.config/nvim/lua/plugins/codecompanion.lua . I did so to make sure it is installed. I am not a lazy vim user.
3. Run :CodeCompanion hello.
4. Run :check health codecompanion 




#82 
Mac OS 13.6 Apple Silicon
ollama version is 0.3.0
NVIM v0.10.0

# Environment

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue
- [X] I have shared the contents of the log file

**Comment by olimorris** [comment]
Assume you're using `deepseek-coder:6.7b` model? That's the default model as per the Ollama.lua file

**Comment by olimorris** [comment]
@Mohamed-E-Fayed you're using custom_llama_3.1 as your model in Ollama but haven't changed the Code Companion config to point to that. You need to amend the adapter settings.

**Comment by Mohamed-E-Fayed** [comment]
Ok! I'm downloading the model now. Could you please give me example of modifying it?!
I'm currently reading ollama.lua you referred to hoping to find how to overwrite that value in init.vim instead of modifying it in codecompanion itself.
I'll update you as soon as I try deepseek-coder:6.7b.
Thank you so much

**Comment by Mohamed-E-Fayed** [comment]
Now, I got another error but in neovim this time.

:CodeCompanion hello
Error executing vim.schedule lua callback: vim/shared.lua:0: s: expected string, got nil                                                                                                                                                    
stack traceback:                                                                                                                                                                                                                                     
        [C]: in function 'error'                                                                                                                                                                                                                     
        vim/shared.lua: in function 'validate'                                                                                                                                                                                                       
        vim/shared.lua: in function 'gsplit'                                                                                                                                                                                                         
        vim/shared.lua: in function 'split'                                                                                                                                                                                                          
        ...decompanion.nvim/lua/codecompanion/strategies/inline.lua:374: in function ''                                                                                                                                                              
        vim/_editor.lua: in function <vim/_editor.lua:0>                                                                                                                                                                                             
Press ENTER or type command to continue                                                                                                                                                                                                              

I’ve tried :CodeCompanionChat and it works!

## Me

Hello

## CodeCompanion

Hello! How can I assist you with your programming or technical queries today?


## Me


This is the same output I get for ollama run deepseek-coder:6.7b.

**Comment by olimorris** [comment]
I've pushed aa5d62c534888e2ae9e12aa683aeaffbecd8f9ce. This will better handle errors from Ollama. Unfortunately, your issue (not selecting a valid Ollama model) was not being returned as an error so the client library in Code Companion (which handles requests) didn't know of it.

This commit adds a callback which checks `stdout` for any errors from Ollama and displays them back to the user. Ultimately you would have been alerted to this had I added this in to the plugin earlier.

**Comment by Mohamed-E-Fayed** [comment]
Thank you so much for your support.

Yes, that would have helped a lot earlier.

Failing silently is a nightmare. The more information the better, unless we are dealing with a very sophisticated system.

That would be appreciated.

I will check the link you provided.

Thank you so much again.
