### ISSUE TITLE
[Bug]: slash_cmd required in custom prompt, or crash

### ISSUE THREAD

**Issue by fredrikaverpil** [olimorris/codecompanion.nvim#87]
### Your `minimal.lua` config

```lua
-- I skipped this part
```

### Error messages

```
   Error  00:10:12 notify.error lazy.nvim Failed to run `config` for codecompanion.nvim

...edrik/lazy/codecompanion.nvim/lua/codecompanion/init.lua:275: attempt to index field 'opts' (a nil value)

# stacktrace:
  - /codecompanion.nvim/lua/codecompanion/init.lua:275 _in_ **setup**
  - ~/.config/fredrik/lua/plugins/codecompanion.lua:34 _in_ **config**
  - ~/.config/fredrik/lua/config/lazy.lua:15
  - ~/.config/fredrik/init.lua:11
```

### Health check output

N/A

### Log output

N/A

### Describe the bug

Right now, you must provide a `slash_cmd` to custom prompts, or there is a crash.

### Reproduce the bug

Add the first custom prompt as described on [this page](https://github.com/olimorris/codecompanion.nvim/blob/main/doc/RECIPES.md#adding-a-prompt-to-the-palette) and the crash/error will be hit, as it does not specify `opts = { slash_cmd = "..." }`.

```lua
require("codecompanion").setup({
  default_prompts = {
    ["My New Prompt"] = {
      strategy = "chat",
      description = "Some cool custom prompt you can do",
      prompts = {
        {
          role = "system",
          content = "You are an experienced developer with Lua and Neovim",
        },
        {
          role = "user_header",
          content = "Can you explain why ..."
        }
      },
    }
  }
})
```

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue
- [X] I have shared the contents of the log file

**Comment by olimorris** [comment]
How and when does the crash occur? When you open the action palette?

**Comment by fredrikaverpil** [comment]
The crash occurs as soon as `require("codecompanion").setup` is called. In my case, when Neovim is launched and plugins are loaded.
