### ISSUE TITLE
[Bug]: Chat content is not modifiable

### ISSUE THREAD

**Issue by niba** [olimorris/codecompanion.nvim#90]
### Your `minimal.lua` config

Default

### Error messages

   Error  23:20:21 msg_show.emsg E21: Cannot make changes, 'modifiable' is off
__

### Health check output

codecompanion.nvim report ~
- Log file: /Users/niba/.local/state/nvim/codecompanion.log
- OK plenary.nvim installed
- OK nvim-treesitter installed
- OK telescope.nvim installed
- OK dressing.nvim installed
- OK curl installed

### Log output

Nothing in logs

### Describe the bug

The chat becomes unmodifiable when I add any selected code using the CodeCompanionAdd command

### Reproduce the bug

1. Open the chat buffer
2. Send anything to the AI
3. Go back to the code buffer
4. Use the CodeCompanionAdd command to move selected code from the code buffer to the chat buffer.
5. Chat buffer is not modifiable

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue
- [X] I have shared the contents of the log file

**Comment by olimorris** [comment]
@niba - I can't seem to recreate this. Is it still an issue for you?

**Comment by niba** [comment]
Yes, I added logs to unlock and lock buff functions

When I ask AI about something i get

> locking
> unlocking

but when I use CodeCompanionAdd to send selected text to chat then I have log

> unlocking
> locking

**Comment by olimorris** [comment]
Thanks again for some thorough analysis!
