### ISSUE TITLE
[Bug]: `inline` strategy no longer inject the response into the current buffer

### ISSUE THREAD

**Issue by huantrinh1802** [olimorris/codecompanion.nvim#92]
### Your `minimal.lua` config

```
  {
    "olimorris/codecompanion.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-treesitter/nvim-treesitter",
      "nvim-telescope/telescope.nvim", -- Optional
      {
        "stevearc/dressing.nvim", -- Optional: Improves the default Neovim UI
        opts = {},
      },
    },
    config = function()
      local session_key = vim.fn.system("cat $TMPDIR/bw_session")
      require("codecompanion").setup({
        adapters = {
          openai = require("codecompanion.adapters").use("openai", {
            env = {
              api_key = ""
            },
            schema = { model = { default = "gpt-4o" } },
          }),
          anthropic = require("codecompanion.adapters").use("anthropic", {
            env = {
              api_key = "",
            },
            schema = { model = { default = "claude-3-5-sonnet-20240620" } },
          }),
        },
        default_prompts = {
          ["Auto-generate git commit message"] = {
            strategy = "inline",
            description = "Generate git commit message for current staged changes",
            opts = {
              mapping = "<LocalLeader>aacm",
            },
            prompts = {
              {
                role = "user",
                contains_code = true,
                content = function()
                  return [[You are an expert at following the Conventional Commit specification                       based on the following diff:
]] .. vim.fn.system("git diff --cached") .. [[

Generate a commit message for me. Follow the below structure:

   [dev | modify | fix] {Summary}

   {List of details if necessary using bullets}

Return the code only and no markdown codeblocks.
                    ]]
                end,
              },
            },
          },
        },
      })
      vim.api.nvim_set_keymap("n", "<leader>aa", "<cmd>CodeCompanionActions<cr>", { noremap = true, silent = true })
      vim.api.nvim_set_keymap("v", "<leader>aa", "<cmd>CodeCompanionActions<cr>", { noremap = true, silent = true })
      vim.api.nvim_set_keymap("n", "<leader>at", "<cmd>CodeCompanionToggle<cr>", { noremap = true, silent = true })
      vim.api.nvim_set_keymap("v", "<leader>at", "<cmd>CodeCompanionToggle<cr>", { noremap = true, silent = true })
    end,
  },
```

### Health check output

codecompanion: require("codecompanion.health").check()

codecompanion.nvim report ~
- Log file: /Users/bentrinh/.local/state/nvim/codecompanion.log
- OK plenary.nvim installed
- OK nvim-treesitter installed
- OK telescope.nvim installed
- OK dressing.nvim installed
- OK curl installed

### Log output

Nothing relevant

### Describe the bug

It used to work few months ago but at the moments, every time inline strategy is used, it opens the chat buffer

![Screenshot 2024-08-10 at 5 31 24 PM](https://github.com/user-attachments/assets/e5c62cd3-30c5-4403-be7e-b12dd3f4724e)

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue
- [X] I have shared the contents of the log file

**Comment by olimorris** [comment]
The example you've given with generating a commit is the intended behaviour. It wouldn't make sense to write the commit into a non-chat buffer.

I'd recommend following the examples in the README.

**Comment by huantrinh1802** [comment]
Could you clarify the `strategy = "inline",` settings? I was assuming with the `inline` strategy, the response would be put into the current buffer. A few months ago, it used to work as what I expected.

**Comment by olimorris** [comment]
So the commit prompt has only been added recently and to my knowledge has always been a `chat` strategy prompt.

As per the readme:

> Strategies are the different ways that a user can interact with the plugin. The chat and agent strategies harness a buffer to allow direct conversation with the LLM. The inline strategy allows for output from the LLM to be written directly into a pre-existing Neovim buffer.

However, as per the [inline.lua](https://github.com/olimorris/codecompanion.nvim/blob/79aee2358ddf914d12a2c318fd788b19ca60d352/lua/codecompanion/strategies/inline.lua#L11-L32) file, the LLM is given the ability to determine where to place its response. It may decide that placing the response in a buffer doesn't make sense and instead send it to a chat buffer, as is happening in your case. You could amend your prompt to ask it to do otherwise.

**Comment by huantrinh1802** [comment]
Hey thanks for reply. After digging in [inline.lua](https://github.com/olimorris/codecompanion.nvim/blob/79aee2358ddf914d12a2c318fd788b19ca60d352/lua/codecompanion/strategies/inline.lua#L11-L32), I discovered the `placement` opts. Initially, my config had the placement as `before`. Currently it needs to be `before|false`. 

```
default_prompts = {
          ["Auto-generate git commit message"] = {
            strategy = "inline",
            description = "Generate git commit message for current staged changes",
            opts = {
              mapping = "<LocalLeader>aacm",
              placement = "before|false"
            },
            prompts = {
              {
                role = "user",
                contains_code = true,
                content = function()
                  return [[You are an expert at following the Conventional Commit specification                       based on the following diff:
]] .. vim.fn.system("git diff --cached") .. [[

Generate a commit message for me. Follow the below structure:

   [dev | modify | fix] {Summary}

   {List of details if necessary using bullets}

Return the code only and no markdown codeblocks.
                    ]]
                end,
              },
            },
          },
```

**Comment by olimorris** [comment]
Great spot! I'd forgotten that was an option. I'll make sure I document this in the `RECIPES.md` file.
